/**
 * A synthetic, offline "mod" resource pack — the modded half of Phase C exit criterion #1
 * (GitHub issue #31).
 *
 * `textures-parity.mjs` proved vanilla parity for real; its own doc comment records exactly
 * why the modded half stayed open: this task's network use is limited to Mojang's own
 * manifest/jar CDN, and no legitimate modded resource pack was reachable to point `--modded`
 * at. Nothing here changes that constraint or pretends to have found a real pack. What it
 * does instead is close the modded half **offline**: every byte below is generated by this
 * file, deterministically, the same way `packages/engine/test/fixtures/vanillaShapedPack.ts`
 * builds its own vanilla-shaped fixture rather than shipping anything from Mojang. A resource
 * pack under a custom namespace, loaded and compared exactly the way a real one would be, is
 * a legitimate test of the *code path* issue #31 asks about — "does a modded pack round-trip
 * through both engines identically" — even though it says nothing about any specific mod.
 *
 * ## What a real mod pack does, and what this one exercises
 *
 * A resource pack that ships with a mod does two things at once, and both are here:
 *
 *   - **adds a new namespace.** `testmod:glowing_ore` and `testmod:resonant_planks` are
 *     brand-new blocks with their own blockstate, block model, item model and texture —
 *     nothing upstream has ever heard of. This is what most of a mod's own pack content
 *     looks like.
 *   - **overrides a vanilla resource.** `assets/minecraft/textures/block/stone.png` is
 *     replaced with a distinct texture (mounted at a *higher* priority than the vanilla
 *     client jar, exactly the way `--resource-pack` / a `packs/` folder entry outranks it on
 *     both engines — see `render-ts.mjs`'s own precedence comment and
 *     `BlueMapService#getPackRoots`). Recolour and "reskin" packs are exactly this shape:
 *     same key, different bytes, higher priority.
 *
 * Both are discovered the same way real assets are: through `DirectorySource`'s
 * `assets/<namespace>/textures/<source>/**\/*.png` walk (upstream: `Atlas#add`/
 * `DirectorySource#load`) — nothing here needs its own atlas file, because
 * `resourceExtensions.zip` (always mounted, on both engines, for every render) already
 * carries a root-level catch-all directory source. Placing the new textures under the
 * conventional `block/` subdirectory means they would still be found even without it, via
 * the client jar's own narrower `block/`-scoped atlas source — the shape a real mod's pack
 * actually relies on.
 *
 * ## Why textures.json, not a rendered world
 *
 * `textures-parity.mjs`'s own header explains why a world's *contents* do not matter to this
 * check: `textures.json` is written from `resourcePack.getTextures()`, which is filled by
 * walking every *loaded* model's texture references, independent of which blocks a world
 * actually contains. `design/packages/worldgen` has no facility for emitting a block under a
 * custom namespace (it generates real Minecraft terrain with real Minecraft block ids, by
 * design), so putting a `testmod:` block into a rendered world is not just extra work, it is
 * not a thing this repository's world generator can do at all. Comparing at the resource-pack
 * / `textures.json` level is the fallback issue #31's own follow-up work names for exactly
 * this situation, and it is what this fixture is for.
 */

import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { posix } from "node:path";
import { solidPng } from "../lib/pngEncode.mjs";

/** Bumped only if this fixture's shape changes in a way that would confuse a stale cache. */
export const SYNTHETIC_MOD_PACK_VERSION = 1;

/** The pack-format this fixture declares. Inert for loading (see `PackMeta.ts`/`.java` — no
 *  loader ever calls `isCompatible`), kept realistic rather than load-bearing. */
const PACK_FORMAT = 34;

/**
 * Every texture key this pack contributes, new namespace and override alike, each with the
 * exact solid colour its texture decodes to — so a caller can prove the pack was genuinely
 * mounted (the right pixels came back) rather than merely present on disk (the key exists,
 * but nothing actually loaded it - see `textures-parity.mjs`'s own check for why key
 * presence alone is not enough for the override case: vanilla's own `minecraft:block/stone`
 * is already a real, busy, multi-coloured texture, so "the key exists" would be true even
 * if this pack's override silently failed to mount and the vanilla texture won instead).
 */
export const SYNTHETIC_MOD_TEXTURES = Object.freeze([
    { key: "testmod:block/glowing_ore", pixel: Object.freeze([255, 140, 0, 255]), newNamespace: true },
    { key: "testmod:block/resonant_planks", pixel: Object.freeze([80, 200, 190, 255]), newNamespace: true },
    // The override: same key vanilla's own stone.json model already references, different
    // bytes, mounted ahead of the client jar. Vanilla's real stone.png is a mottled grey
    // texture with no flat run of pixels this colour, so this value could not appear by
    // accident - only by this pack's override actually taking priority.
    { key: "minecraft:block/stone", pixel: Object.freeze([90, 40, 160, 255]), newNamespace: false },
]);

/** Just the keys, for a caller that only needs presence rather than the expected pixel. */
export const SYNTHETIC_MOD_TEXTURE_KEYS = Object.freeze(SYNTHETIC_MOD_TEXTURES.map((t) => t.key));

/** Every block id this pack defines under its own namespace (the override is not one). */
export const SYNTHETIC_MOD_BLOCK_KEYS = Object.freeze(["testmod:glowing_ore", "testmod:resonant_planks"]);

function json(value) {
    return JSON.stringify(value, null, 2) + "\n";
}

/** A cube_all-parented block: one blockstate, one block model, one item model, one texture. */
async function writeCubeAllBlock(root, { id, pixel }) {
    const [namespace, name] = id.split(":");

    await mkdir(join(root, "assets", namespace, "blockstates"), { recursive: true });
    await writeFile(
        join(root, "assets", namespace, "blockstates", `${name}.json`),
        json({ variants: { "": { model: `${namespace}:block/${name}` } } }),
    );

    await mkdir(join(root, "assets", namespace, "models", "block"), { recursive: true });
    await writeFile(
        join(root, "assets", namespace, "models", "block", `${name}.json`),
        json({ parent: "minecraft:block/cube_all", textures: { all: `${namespace}:block/${name}` } }),
    );

    await mkdir(join(root, "assets", namespace, "models", "item"), { recursive: true });
    await writeFile(
        join(root, "assets", namespace, "models", "item", `${name}.json`),
        json({ parent: `${namespace}:block/${name}` }),
    );

    await mkdir(join(root, "assets", namespace, "textures", "block"), { recursive: true });
    await writeFile(
        join(root, "assets", namespace, "textures", "block", `${name}.png`),
        solidPng(16, 16, pixel),
    );
}

/**
 * Builds the pack fresh under `destDir`, replacing whatever was there.
 *
 * Deterministic and cheap (a handful of small in-memory PNGs), so callers regenerate it on
 * every run rather than caching it — the one thing worth caching here is the *render*, not
 * the fixture that feeds it, and `javaOracle.mjs`/`textures-parity.mjs` already key their own
 * cache off a hash of this pack's content for exactly that reason.
 *
 * @param {string} destDir
 * @returns {Promise<{directory: string, textureKeys: readonly string[], blockKeys: readonly string[]}>}
 */
export async function buildSyntheticModPack(destDir) {
    await rm(destDir, { recursive: true, force: true });
    await mkdir(destDir, { recursive: true });

    await writeFile(
        join(destDir, "pack.mcmeta"),
        json({
            pack: {
                pack_format: PACK_FORMAT,
                description:
                    "Synthetic offline mod pack for issue #31's textures.json parity check " +
                    "(tools/oracle/fixtures/syntheticModPack.mjs) - not a real mod",
            },
        }),
    );

    // A brand-new namespace: two unrelated blocks, so the fixture is "a handful", not one.
    for (const texture of SYNTHETIC_MOD_TEXTURES) {
        if (!texture.newNamespace) continue;
        const [namespace, path] = texture.key.split(":");
        const name = path.split("/").pop();
        await writeCubeAllBlock(destDir, { id: `${namespace}:${name}`, pixel: texture.pixel });
    }

    // A vanilla override: same resource key as the real stone texture, different bytes,
    // mounted ahead of the client jar - the "reskin" shape a real mod pack also ships.
    const override = SYNTHETIC_MOD_TEXTURES.find((t) => !t.newNamespace);
    const [overrideNamespace, overridePath] = override.key.split(":");
    const overrideDir = posix.dirname(overridePath); // "block/stone" -> "block"
    const overrideFile = posix.basename(overridePath); // "block/stone" -> "stone"
    await mkdir(join(destDir, "assets", overrideNamespace, "textures", overrideDir), {
        recursive: true,
    });
    await writeFile(
        join(destDir, "assets", overrideNamespace, "textures", overrideDir, `${overrideFile}.png`),
        solidPng(16, 16, override.pixel),
    );

    return {
        directory: destDir,
        textureKeys: SYNTHETIC_MOD_TEXTURE_KEYS,
        blockKeys: SYNTHETIC_MOD_BLOCK_KEYS,
        textures: SYNTHETIC_MOD_TEXTURES,
    };
}
