import { PNG } from "pngjs";
import { buildZip, type ZipTestEntry } from "../../src/resources/pack/vfs/zipTestUtil.js";

/*
 * Test-support only — not part of the upstream port, so this file carries no
 * `upstream:` header.
 *
 * Builds a synthetic, *vanilla-shaped* resource-pack jar entirely in memory: every byte
 * (png, mcmeta, json, zip container) is generated by the code below at test-time. Nothing
 * pre-baked lives under `test/fixtures/`, and nothing that came from Mojang ever may —
 * see the licensing note in packages/engine/README.md.
 *
 * "Vanilla-shaped" means the directory layout and the file-shapes a real client-jar uses
 * (`assets/<namespace>/{atlases,blockstates,models,textures}/…`, `pack.mcmeta`, a
 * `minecraft:directory` atlas-source), *not* vanilla content: every key is prefixed
 * `e2e_` so nothing here can be mistaken for a real Minecraft resource.
 *
 * The pack is deliberately built so that each link of the resolution chain has something
 * to prove:
 *
 *   blockstate  `minecraft:e2e_block`  two property-conditioned variant-sets, no default
 *                                      -> Variants condition matching is load-bearing
 *   variant-set `lit=false`            two variants, weights 1 and 3
 *                                      -> VariantSet's position-hash selection is load-bearing
 *   model chain e2e_block -> cube_all -> block
 *                                      -> applyParent has to walk TWO levels
 *   textures    "#all" -> "all" -> "#tinted" -> "tinted" -> minecraft:block/e2e_stone
 *                                      -> TextureVariable indirection is load-bearing
 *   texture     e2e_unused.png         referenced by nothing
 *                                      -> the used-texture filter is load-bearing
 */

// #region generated images

/** one rgba pixel, as the fixture writes it and as `Texture#getTextureImage` reads it back */
export type Pixel = [r: number, g: number, b: number, a: number];

function image(width: number, height: number, paint: (x: number, y: number) => Pixel): Buffer {
    const png = new PNG({ width, height });
    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const [r, g, b, a] = paint(x, y);
            const i = (width * y + x) << 2;
            png.data[i] = r;
            png.data[i + 1] = g;
            png.data[i + 2] = b;
            png.data[i + 3] = a;
        }
    }
    return PNG.sync.write(png);
}

function solid(width: number, height: number, pixel: Pixel): Buffer {
    return image(width, height, () => pixel);
}

/** the pixel the fixture paints at every unmarked position of `block/e2e_stone` */
export const E2E_STONE_FIELD: Pixel = [120, 120, 120, 255];
/** the marker `block/e2e_stone` carries at (0, 0) */
export const E2E_STONE_TOP_LEFT: Pixel = [255, 0, 0, 255];
/** the marker `block/e2e_stone` carries at (15, 15) */
export const E2E_STONE_BOTTOM_RIGHT: Pixel = [0, 0, 255, 255];

/**
 * The end-to-end target texture: a 16x16 field with two corner markers, so an assertion
 * on its pixels can only pass if the *right* texture was resolved and decoded.
 */
function e2eStonePng(): Buffer {
    return image(16, 16, (x, y) => {
        if (x === 0 && y === 0) return E2E_STONE_TOP_LEFT;
        if (x === 15 && y === 15) return E2E_STONE_BOTTOM_RIGHT;
        return E2E_STONE_FIELD;
    });
}

// #endregion
// #region generated json

/** the pack-format the fixture declares; the test builds its `PackVersion` from this */
export const PACK_FORMAT = 34;

const PACK_MCMETA = JSON.stringify({
    pack: { pack_format: PACK_FORMAT, description: "e2e fixture" },
});

const BLOCKS_ATLAS_JSON = JSON.stringify({
    sources: [{ type: "minecraft:directory", source: "block", prefix: "block/" }],
});

/**
 * Two property-conditioned variant-sets and no `""` / `"default"` member — so a
 * world-blockstate that carries no `lit` property matches nothing at all, and the
 * condition-matching step cannot be short-circuited by a default variant.
 *
 * The `lit=false` set holds two variants with weights 1 and 3 (total 4), so
 * `VariantSet#forEach(x, y, z, …)` picks the first one exactly when
 * `hashToFloat(x, y, z) < 0.25`.
 */
export const E2E_BLOCK_BLOCKSTATE_JSON = JSON.stringify({
    variants: {
        "lit=false": [
            { model: "minecraft:block/e2e_block", weight: 1 },
            { model: "minecraft:block/e2e_block_alt", weight: 3 },
        ],
        "lit=true": { model: "minecraft:block/e2e_block_lit" },
    },
});

/**
 * The root of the model-chain. It declares no elements — only a texture-variable and an
 * `ambientocclusion`, both of which have to travel two levels down to the leaf.
 */
export const BLOCK_MODEL_JSON = JSON.stringify({
    textures: { fallback_only: "minecraft:block/e2e_fallback" },
    ambientocclusion: false,
});

/** the middle of the model-chain: it supplies the full-cube element and a `#all` reference */
export const CUBE_ALL_MODEL_JSON = JSON.stringify({
    parent: "minecraft:block/block",
    textures: { particle: "#all" },
    elements: [
        {
            from: [0, 0, 0],
            to: [16, 16, 16],
            faces: {
                down: { texture: "#all", cullface: "down" },
                up: { texture: "#all", cullface: "up" },
                north: { texture: "#all", cullface: "north" },
                south: { texture: "#all", cullface: "south" },
                west: { texture: "#all", cullface: "west" },
                east: { texture: "#all", cullface: "east" },
            },
        },
    ],
});

/**
 * The leaf of the model-chain. `all` is a `#reference` to `tinted` rather than a path, so
 * a face's `#all` has to hop twice — `#all` -> `all` -> `#tinted` -> `tinted` — before it
 * reaches a {@code ResourcePath}.
 */
export const E2E_BLOCK_MODEL_JSON = JSON.stringify({
    parent: "minecraft:block/cube_all",
    textures: {
        all: "#tinted",
        tinted: "minecraft:block/e2e_stone",
        overlay: "minecraft:block/e2e_glass",
        flow: "minecraft:block/e2e_water",
    },
});

const E2E_BLOCK_ALT_MODEL_JSON = JSON.stringify({
    parent: "minecraft:block/cube_all",
    textures: { all: "minecraft:block/e2e_amber" },
});

const E2E_BLOCK_LIT_MODEL_JSON = JSON.stringify({
    parent: "minecraft:block/cube_all",
    textures: { all: "minecraft:block/e2e_lamp" },
});

/** the sibling `<texture>.png.mcmeta` that gives `block/e2e_lamp` an animation */
const E2E_LAMP_MCMETA = JSON.stringify({ animation: { frametime: 3, interpolate: true } });

// #endregion
// #region the pack

/**
 * Builds the fixture jar.
 *
 * The texture-entries are deliberately written in a *scrambled* order (water, stone,
 * glass, lamp, amber, fallback, unused). A `ZipFileSystem` lists a directory in
 * central-directory order, so the texture-pool ends up in this order too — which means an
 * assertion on `TextureGallery`'s opaque-first, then key-sorted ordinals can only
 * pass if the gallery really sorted, rather than happening to inherit pool-order.
 */
export function vanillaShapedPackZip(): Buffer {
    const entries: ZipTestEntry[] = [
        { name: "pack.mcmeta", data: PACK_MCMETA },

        { name: "assets/minecraft/atlases/blocks.json", data: BLOCKS_ATLAS_JSON },

        { name: "assets/minecraft/blockstates/e2e_block.json", data: E2E_BLOCK_BLOCKSTATE_JSON },
        // not a resource — proves the ".json" filter, and that a stray file is harmless
        { name: "assets/minecraft/blockstates/notes.txt", data: "not a resource" },

        { name: "assets/minecraft/models/block/block.json", data: BLOCK_MODEL_JSON },
        { name: "assets/minecraft/models/block/cube_all.json", data: CUBE_ALL_MODEL_JSON },
        { name: "assets/minecraft/models/block/e2e_block.json", data: E2E_BLOCK_MODEL_JSON },
        {
            name: "assets/minecraft/models/block/e2e_block_alt.json",
            data: E2E_BLOCK_ALT_MODEL_JSON,
        },
        {
            name: "assets/minecraft/models/block/e2e_block_lit.json",
            data: E2E_BLOCK_LIT_MODEL_JSON,
        },

        // -- textures, in an order that is neither alphabetical nor the expected gallery order --
        {
            name: "assets/minecraft/textures/block/e2e_water.png",
            data: solid(16, 16, [0, 80, 200, 90]),
        },
        { name: "assets/minecraft/textures/block/e2e_stone.png", data: e2eStonePng() },
        {
            name: "assets/minecraft/textures/block/e2e_glass.png",
            data: solid(16, 16, [100, 150, 255, 128]),
        },
        {
            name: "assets/minecraft/textures/block/e2e_lamp.png",
            data: solid(16, 32, [250, 250, 200, 255]),
        },
        { name: "assets/minecraft/textures/block/e2e_lamp.png.mcmeta", data: E2E_LAMP_MCMETA },
        {
            name: "assets/minecraft/textures/block/e2e_amber.png",
            data: solid(16, 16, [255, 170, 0, 255]),
        },
        {
            name: "assets/minecraft/textures/block/e2e_fallback.png",
            data: solid(16, 16, [10, 20, 30, 255]),
        },
        // referenced by no model at all — the used-texture filter has to keep it out
        {
            name: "assets/minecraft/textures/block/e2e_unused.png",
            data: solid(16, 16, [1, 2, 3, 255]),
        },
    ];

    return buildZip(entries);
}

// #endregion
