/**
 * Reading a `SHA256SUMS`, including the lines that must never be quietly skipped.
 *
 * The fixture is the real one: the four digests published beside the 6.6 GB Andyville
 * world, copied verbatim from `SHA256SUMS` on that release.
 */

import { describe, expect, it } from "vitest";
import {
    ChecksumFileError,
    checksumsByName,
    isChecksumAssetName,
    parseChecksums,
} from "./checksums.js";

const ANDYVILLE = [
    "f9ae56e9236e428936d951170eeed90b80b7c48a3d38ac7435b7c70933ae522d  andyville-world-20260804-160001.zip.part.0000",
    "32d21c078eced4f676423301a3ed5bcc43314280d4fb056d26ecc3622e8083f6  andyville-world-20260804-160001.zip.part.0001",
    "9cf68a9b5f20e326b5cae75e036fdc38ff3e9cd52cb28ea2a439c89fa40e43b3  andyville-world-20260804-160001.zip.part.0002",
    "257bf7156c1e5dd4a55dba6f0d3dc3deeb8e5918f16152d5ddea34ff11f9808c  andyville-world-20260804-160001.zip.part.0003",
    "",
].join("\n");

describe("parseChecksums", () => {
    it("reads the real Andyville SHA256SUMS", () => {
        const entries = parseChecksums(ANDYVILLE, "SHA256SUMS");
        expect(entries).toHaveLength(4);
        expect(entries[0]).toEqual({
            name: "andyville-world-20260804-160001.zip.part.0000",
            sha256: "f9ae56e9236e428936d951170eeed90b80b7c48a3d38ac7435b7c70933ae522d",
        });
        expect(entries[3]?.name).toBe("andyville-world-20260804-160001.zip.part.0003");
    });

    it("reads binary-mode lines, tabs, comments and blank lines", () => {
        const entries = parseChecksums(
            ["# generated by a backup script", "", `${"a".repeat(64)} *world.zip.001`, `${"b".repeat(64)}\tworld.zip.002`].join(
                "\n",
            ),
            "sums",
        );
        expect(entries.map((entry) => entry.name)).toEqual(["world.zip.001", "world.zip.002"]);
    });

    it("reads the BSD spelling too, because both are in the wild", () => {
        const entries = parseChecksums(`SHA256 (world.zip.001) = ${"c".repeat(64)}`, "sums");
        expect(entries).toEqual([{ name: "world.zip.001", sha256: "c".repeat(64) }]);
    });

    it("lower-cases the digest so a comparison cannot fail on case alone", () => {
        const entries = parseChecksums(`${"A".repeat(64)}  world.zip.001`, "sums");
        expect(entries[0]?.sha256).toBe("a".repeat(64));
    });

    it("refuses a file rather than returning the lines it understood", () => {
        // A partial parse is the dangerous outcome: the parts named by the lines that
        // were skipped would then be joined with nothing checking them.
        expect(() =>
            parseChecksums([`${"a".repeat(64)}  world.zip.001`, "this line is not a digest"].join("\n"), "sums"),
        ).toThrow(ChecksumFileError);
    });

    it("refuses a name that is not a plain file name", () => {
        for (const name of ["../../../.ssh/authorized_keys", "/etc/passwd", "C:\\windows\\x", ".."]) {
            expect(() => parseChecksums(`${"a".repeat(64)}  ${name}`, "sums")).toThrow(
                ChecksumFileError,
            );
        }
    });

    it("refuses two digests for one name, because neither can be trusted", () => {
        expect(() =>
            parseChecksums(
                [`${"a".repeat(64)}  world.zip.001`, `${"b".repeat(64)}  world.zip.001`].join("\n"),
                "sums",
            ),
        ).toThrow(/twice/);
    });

    it("refuses an empty list", () => {
        expect(() => parseChecksums("# nothing here\n\n", "sums")).toThrow(/no checksums/);
    });

    it("names the file and the line, because a release has several", () => {
        expect(() => parseChecksums("nope", "SHA256SUMS")).toThrow(/SHA256SUMS line 1/);
    });
});

describe("isChecksumAssetName", () => {
    it("knows the names a publisher actually uses", () => {
        expect(isChecksumAssetName("SHA256SUMS")).toBe(true);
        expect(isChecksumAssetName("checksums.txt")).toBe(true);
        // Deliberately not a pattern: verifying a world against last release's list would
        // fail loudly for the right reason with the wrong evidence.
        expect(isChecksumAssetName("SHA256SUMS-old-release.txt")).toBe(false);
        expect(isChecksumAssetName("world.zip")).toBe(false);
    });
});

describe("checksumsByName", () => {
    it("turns the list into the lookup a verification pass uses", () => {
        const map = checksumsByName(parseChecksums(ANDYVILLE, "SHA256SUMS"));
        expect(map.get("andyville-world-20260804-160001.zip.part.0002")).toBe(
            "9cf68a9b5f20e326b5cae75e036fdc38ff3e9cd52cb28ea2a439c89fa40e43b3",
        );
        expect(map.size).toBe(4);
    });
});
