import { mkdir } from "node:fs/promises";
import { basename } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Key } from "@material-bluemap/shared";
import type { PNG } from "pngjs";
import { TextureGallery } from "../src/map/TextureGallery.js";
import { MinecraftVersion } from "../src/resources/MinecraftVersion.js";
import { parse } from "../src/resources/adapter/JsonMapper.js";
import { PackVersion } from "../src/resources/pack/PackVersion.js";
import { ResourcePack } from "../src/resources/pack/resourcepack/ResourcePack.js";
import type { BlockState as PackBlockState } from "../src/resources/pack/resourcepack/blockstate/BlockState.js";
import type { Variant } from "../src/resources/pack/resourcepack/blockstate/Variant.js";
import { hashToFloat } from "../src/resources/pack/resourcepack/blockstate/VariantSet.js";
import { Model } from "../src/resources/pack/resourcepack/model/Model.js";
import { DirFileSystem } from "../src/resources/pack/vfs/DirFileSystem.js";
import { ZipFileSystem } from "../src/resources/pack/vfs/ZipFileSystem.js";
import { Direction } from "../src/util/Direction.js";
import { BlockState as WorldBlockState } from "../src/world/BlockState.js";
import {
    E2E_BLOCK_MODEL_JSON,
    E2E_STONE_BOTTOM_RIGHT,
    E2E_STONE_FIELD,
    E2E_STONE_TOP_LEFT,
    PACK_FORMAT,
    vanillaShapedPackZip,
    type Pixel,
} from "./fixtures/vanillaShapedPack.js";

/*
 * Wave C4-2 — the three end-to-end proofs that close Phase C.
 *
 *   Proof 1  offline; runs on every `pnpm test`. Resolves a block all the way from a
 *            blockstate-json down to real texture pixels over a synthetic, vanilla-shaped
 *            pack, then indexes that pack's textures with a TextureGallery.
 *   Proof 2  the live check against a real Minecraft client-jar. OPT-IN, and skipped by
 *            default — it downloads from Mojang's servers, so it needs both an env-var and
 *            the accept-download consent flag. See packages/engine/README.md.
 *   Proof 3  the shape of the textures.json document, asserted against upstream's
 *            *serialization contract as read from the java source*. It is NOT a comparison
 *            against java output — see the note on that describe-block.
 *
 * Everything these tests read is generated by test/fixtures/vanillaShapedPack.ts, except
 * proof 2, which reads a client-jar the runner downloaded and which is never committed.
 */

// #region shared helpers

/** the rgba pixel at (x, y) of a decoded texture-image */
function pixel(image: PNG, x: number, y: number): Pixel {
    const i = (image.width * y + x) << 2;
    return [image.data[i]!, image.data[i + 1]!, image.data[i + 2]!, image.data[i + 3]!];
}

/** every variant the given resourcepack-blockstate selects for a world-block at (x, y, z) */
function selectAt(
    resource: PackBlockState,
    state: WorldBlockState,
    x: number,
    y: number,
    z: number,
): Variant[] {
    const selected: Variant[] = [];
    resource.forEach(state, x, y, z, (variant) => selected.push(variant));
    return selected;
}

function worldBlock(id: string, properties: Record<string, string> = {}): WorldBlockState {
    return new WorldBlockState(Key.minecraft(id), new Map(Object.entries(properties)));
}

beforeEach(() => {
    // the pack-loader logs its phases through the console (see ResourcePack.ts)
    vi.spyOn(console, "debug").mockImplementation(() => {});
    vi.spyOn(console, "info").mockImplementation(() => {});
    vi.spyOn(console, "warn").mockImplementation(() => {});
});

afterEach(() => {
    vi.restoreAllMocks();
});

// #endregion
// #region proof 1 — the offline resolution chain

/** the fixture pack, mounted from the in-memory jar and fully loaded + baked */
async function loadFixturePack(): Promise<ResourcePack> {
    const fileSystem = await ZipFileSystem.fromBuffer(vanillaShapedPackZip(), "e2e-fixture.jar");
    const pack = new ResourcePack(new PackVersion(PACK_FORMAT, 0));
    await pack.loadResources(fileSystem.getRootDirectories());
    return pack;
}

const E2E_BLOCK = Key.minecraft("e2e_block");
const E2E_STONE_TEXTURE = Key.minecraft("block/e2e_stone");
const E2E_UNUSED_TEXTURE = Key.minecraft("block/e2e_unused");

/**
 * The ordinals `TextureGallery#put(ResourcePool)` has to hand out for the fixture pack:
 * the missing-texture first, then the opaque textures in formatted-key order, then the
 * half-transparent ones in formatted-key order. None of this is the pool's own order —
 * the fixture writes its texture-entries scrambled on purpose.
 */
const EXPECTED_GALLERY_ORDER: readonly string[] = [
    "bluemap:block/missing",
    // opaque (getColorPremultiplied().a === 1)
    "minecraft:block/e2e_amber",
    "minecraft:block/e2e_fallback",
    "minecraft:block/e2e_lamp",
    "minecraft:block/e2e_stone",
    // half-transparent (getColorPremultiplied().a < 1)
    "minecraft:block/e2e_glass",
    "minecraft:block/e2e_water",
];

describe("Proof 1 — a block resolves end-to-end over a synthetic vanilla-shaped pack", () => {
    it("matches a Variants condition, and matches nothing when the condition cannot hold", async () => {
        const pack = await loadFixturePack();

        const resource = pack.getBlockStates().get(E2E_BLOCK);
        expect(resource).not.toBeNull();

        const variants = resource!.getVariants();
        expect(variants).not.toBeNull();
        // the fixture declares no "" / "default" member, so nothing can fall through
        expect(variants!.getDefaultVariant()).toBeNull();
        expect(variants!.getVariants().length).toBe(2);

        // lit=true selects the single-variant set …
        const litSelection = selectAt(resource!, worldBlock("e2e_block", { lit: "true" }), 0, 0, 0);
        expect(litSelection.length).toBe(1);
        expect(litSelection[0]!.getModel().getFormatted()).toBe("minecraft:block/e2e_block_lit");

        // … and a block that carries no `lit` property at all matches neither condition
        expect(selectAt(resource!, worldBlock("e2e_block"), 0, 0, 0)).toEqual([]);
    });

    it("selects a weighted variant by position, deterministically", async () => {
        const pack = await loadFixturePack();
        const resource = pack.getBlockStates().get(E2E_BLOCK)!;
        const unlit = worldBlock("e2e_block", { lit: "false" });

        // the fixture's lit=false set holds weights 1 and 3 (total 4), so
        // VariantSet#forEach picks the first variant exactly when hashToFloat < 0.25
        expect(hashToFloat(0, 0, 0)).toBeLessThan(0.25);
        expect(hashToFloat(0, 0, 1)).toBeGreaterThanOrEqual(0.25);

        const atOrigin = selectAt(resource, unlit, 0, 0, 0);
        expect(atOrigin.length).toBe(1);
        expect(atOrigin[0]!.getModel().getFormatted()).toBe("minecraft:block/e2e_block");

        const atNeighbour = selectAt(resource, unlit, 0, 0, 1);
        expect(atNeighbour.length).toBe(1);
        expect(atNeighbour[0]!.getModel().getFormatted()).toBe("minecraft:block/e2e_block_alt");

        // the same coordinate always yields the same variant — it is a position-hash, not a prng
        expect(selectAt(resource, unlit, 0, 0, 0)[0]).toBe(atOrigin[0]);
        expect(selectAt(resource, unlit, 0, 0, 1)[0]).toBe(atNeighbour[0]);
    });

    it("resolves the selected variant's model through a two-level parent chain", async () => {
        const pack = await loadFixturePack();
        const resource = pack.getBlockStates().get(E2E_BLOCK)!;

        const variant = selectAt(resource, worldBlock("e2e_block", { lit: "false" }), 0, 0, 0)[0]!;
        const model = variant.getModel().getResource((key) => pack.getModels().get(key));
        expect(model).not.toBeNull();

        // applyParent nulls the parent-path as it walks, so a baked model has none left
        expect(model!.getParent()).toBeNull();

        // one level up (block/cube_all): the element and the "particle" variable
        expect(model!.getElements()).not.toBeNull();
        expect(model!.getElements()!.length).toBe(1);
        expect(model!.getTextures().has("particle")).toBe(true);

        // two levels up (block/block): a variable and an ambientocclusion that only the
        // grandparent declares — they can only be here if applyParent recursed
        expect(model!.getTextures().has("fallback_only")).toBe(true);
        expect(model!.isAmbientocclusion()).toBe(false);

        // calculateProperties then found six faces backed by an opaque texture
        expect(model!.isOccluding()).toBe(true);
        expect(model!.isCulling()).toBe(true);
    });

    it("follows the #reference texture-variable indirection to the real texture pixels", async () => {
        const pack = await loadFixturePack();
        const resource = pack.getBlockStates().get(E2E_BLOCK)!;
        const variant = selectAt(resource, worldBlock("e2e_block", { lit: "false" }), 0, 0, 0)[0]!;
        const model = variant.getModel().getResource((key) => pack.getModels().get(key))!;

        // as parsed, "all" really is a reference to "tinted" — the indirection below is
        // not an artefact of the fixture already holding a path
        const asParsed = Model.Adapter.read(parse(E2E_BLOCK_MODEL_JSON));
        const parsedAll = asParsed.getTextures().get("all")!;
        expect(parsedAll.isReference()).toBe(true);
        expect(parsedAll.getReferenceName()).toBe("tinted");
        expect(parsedAll.getTexturePath()).toBeNull();

        // the face names "#all", which has to hop "all" -> "#tinted" -> "tinted"
        const face = model.getElements()![0]!.getFaces().get(Direction.UP);
        expect(face).toBeDefined();

        const texturePath = face!
            .getTexture()
            .getTexturePath((name) => model.getTextures().get(name) ?? null);
        expect(texturePath).not.toBeNull();
        expect(texturePath!.getFormatted()).toBe("minecraft:block/e2e_stone");

        // it is the very ResourcePath object declared under "tinted": resolveTexturePath
        // assigns the referenced variable's own path, so identity proves the hop happened
        expect(texturePath).toBe(model.getTextures().get("tinted")!.getTexturePath());

        const texture = texturePath!.getResource((key) => pack.getTextures().get(key));
        expect(texture).not.toBeNull();
        expect(texture!.getKey().getFormatted()).toBe("minecraft:block/e2e_stone");

        // … and the decoded image is the one the fixture painted, marker pixels and all
        const decoded = texture!.getTextureImage();
        expect([decoded.width, decoded.height]).toEqual([16, 16]);
        expect(pixel(decoded, 0, 0)).toEqual(E2E_STONE_TOP_LEFT);
        expect(pixel(decoded, 15, 15)).toEqual(E2E_STONE_BOTTOM_RIGHT);
        expect(pixel(decoded, 8, 8)).toEqual(E2E_STONE_FIELD);
    });

    it("keeps a texture no model references out of the pool", async () => {
        const pack = await loadFixturePack();

        expect(pack.getTextures().get(E2E_STONE_TEXTURE)).not.toBeNull();
        expect(pack.getTextures().get(E2E_UNUSED_TEXTURE)).toBeNull();
    });
});

describe("Proof 1 — the TextureGallery over that pack", () => {
    it("gives ordinal 0 to bluemap:block/missing, then opaque-first and key-sorted", async () => {
        const pack = await loadFixturePack();

        const gallery = new TextureGallery();
        gallery.put(pack.getTextures());

        const written = JSON.parse(gallery.writeTexturesFile()) as { resourcePath: string }[];
        expect(written.map((texture) => texture.resourcePath)).toEqual(EXPECTED_GALLERY_ORDER);

        // the gallery's own lookup agrees with the document it wrote
        expect(gallery.get(Key.bluemap("block/missing"))).toBe(0);
        EXPECTED_GALLERY_ORDER.forEach((formatted, ordinal) => {
            expect(gallery.get(Key.parse(formatted))).toBe(ordinal);
        });

        // an unknown key falls back to the missing-texture's ordinal
        expect(gallery.get(E2E_UNUSED_TEXTURE)).toBe(0);
    });

    it("preserves every ordinal across a write -> read round trip", async () => {
        const pack = await loadFixturePack();

        const gallery = new TextureGallery();
        gallery.put(pack.getTextures());
        const document = gallery.writeTexturesFile();

        const reread = TextureGallery.readTexturesFile(document);

        EXPECTED_GALLERY_ORDER.forEach((formatted, ordinal) => {
            expect(reread.get(Key.parse(formatted))).toBe(ordinal);
        });

        // re-writing the re-read gallery lands every key back on the same index, which is
        // what a re-loaded resource-pack has to do for already-rendered tiles to keep
        // pointing at the textures they were rendered against
        const rewritten = JSON.parse(reread.writeTexturesFile()) as { resourcePath: string }[];
        expect(rewritten.map((texture) => texture.resourcePath)).toEqual(EXPECTED_GALLERY_ORDER);

        // note: the *animation* member deliberately does not survive the round trip —
        // upstream's writer and reader disagree, which is pinned bug-for-bug by
        // src/resources/pack/resourcepack/texture/Texture.test.ts. Only the ordinals are
        // claimed here.
    });
});

// #endregion
// #region proof 3 — the shape of textures.json

/**
 * Upstream's serialization contract for `textures.json`, read from the java source at
 * vendor/BlueMap (tag-free `main` tree, commit e664c1a):
 *
 *   core/…/map/TextureGallery.java
 *     - `GSON.toJson(textures, Texture[].class, writer)` — a BARE ARRAY indexed by ordinal,
 *       built with `ResourcesGson.addAdapter(new GsonBuilder())` plus
 *       `FieldNamingPolicy.IDENTITY`, so member-names are the java field-names verbatim.
 *   core/…/resources/pack/resourcepack/texture/Texture.java
 *     - `@SerializedName("resourcePath") private Key key` — the member is `resourcePath`,
 *       NOT `key`.
 *     - `private Color color`, `private boolean halfTransparent`, `private String texture`.
 *     - `@Nullable private AnimationMeta animation` — gson does not serialize nulls by
 *       default, so the member is OMITTED when there is no animation.
 *     - the texture-string is `TEXTURE_STRING_PREFIX + base64`, i.e. `data:image/png;base64,…`.
 *   core/…/resources/adapter/ColorAdapter.java
 *     - `write` calls `value.straight()` then emits `[r, g, b, a]` — a four-number array.
 *
 * THIS IS A SHAPE ASSERTION, NOT A DIFF AGAINST JAVA. No java output has been generated or
 * compared; there is no oracle yet (that is issue #3). Do not read a passing run here as
 * "matches BlueMap" — it says only that the document has the members upstream's gson would
 * emit, with the types it would emit them as.
 *
 * WHEN THE ORACLE LANDS: keep this block (a shape failure is a clearer diagnosis than a
 * byte diff) and add a sibling test that loads the java-produced `textures.json` for the
 * same pack and compares parsed element-for-element — resourcePath and ordinal exactly,
 * color within a float32 epsilon, and the decoded png pixel-for-pixel rather than by
 * base64 string, since two png encoders may disagree on chunk layout for identical pixels.
 */
describe("Proof 3 — textures.json has the shape upstream's gson would emit", () => {
    const TEXTURE_URI_PREFIX = "data:image/png;base64,";

    async function texturesJson(): Promise<unknown> {
        const pack = await loadFixturePack();
        const gallery = new TextureGallery();
        gallery.put(pack.getTextures());
        return JSON.parse(gallery.writeTexturesFile());
    }

    it("is a bare array indexed by ordinal, not an object", async () => {
        const document = await texturesJson();

        expect(Array.isArray(document)).toBe(true);
        expect((document as unknown[]).length).toBe(EXPECTED_GALLERY_ORDER.length);
    });

    it("carries resourcePath / color / halfTransparent / texture on every element", async () => {
        const elements = (await texturesJson()) as Record<string, unknown>[];

        for (const element of elements) {
            const members = Object.keys(element).sort();
            // `animation` is the only optional member; nothing else may appear
            expect(members.filter((name) => name !== "animation")).toEqual([
                "color",
                "halfTransparent",
                "resourcePath",
                "texture",
            ]);

            // the java field is `key`; the wire member is `resourcePath`
            expect(element["key"]).toBeUndefined();
            expect(typeof element["resourcePath"]).toBe("string");
            expect(Key.parse(element["resourcePath"] as string).getFormatted()).toBe(
                element["resourcePath"],
            );

            // ColorAdapter#write -> [r, g, b, a]. Four finite numbers is the whole
            // contract — gson writes raw floats, so no range is promised (and asserting
            // one would be a float-epsilon flake on a straight()-divided average).
            const color = element["color"];
            expect(Array.isArray(color)).toBe(true);
            expect((color as unknown[]).length).toBe(4);
            for (const channel of color as unknown[]) {
                expect(typeof channel).toBe("number");
                expect(Number.isFinite(channel as number)).toBe(true);
                expect(channel as number).toBeGreaterThanOrEqual(0);
            }

            expect(typeof element["halfTransparent"]).toBe("boolean");
            expect(typeof element["texture"]).toBe("string");
            expect(element["texture"] as string).toMatch(/^data:image\/png;base64,/);
        }
    });

    it("encodes the texture as a decodable data:image/png;base64 uri", async () => {
        const elements = (await texturesJson()) as Record<string, unknown>[];

        const stone = elements.find(
            (element) => element["resourcePath"] === "minecraft:block/e2e_stone",
        );
        expect(stone).toBeDefined();

        const uri = stone!["texture"] as string;
        const base64 = uri.substring(TEXTURE_URI_PREFIX.length);
        const bytes = Buffer.from(base64, "base64");
        // the png signature — the uri really holds png bytes, not an opaque blob
        expect([...bytes.subarray(0, 8)]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    });

    it("omits `animation` when there is none, and emits it when there is", async () => {
        const elements = (await texturesJson()) as Record<string, unknown>[];

        const stone = elements.find(
            (element) => element["resourcePath"] === "minecraft:block/e2e_stone",
        )!;
        expect("animation" in stone).toBe(false);

        // the fixture gives block/e2e_lamp a sibling .png.mcmeta
        const lamp = elements.find(
            (element) => element["resourcePath"] === "minecraft:block/e2e_lamp",
        )!;
        expect("animation" in lamp).toBe(true);
        expect(lamp["animation"]).toEqual({
            interpolate: true,
            width: 1,
            height: 1,
            frametime: 3,
        });
    });
});

// #endregion
// #region proof 2 — the live client-jar check (opt-in; skipped by default)

/** set to `1` to run the live proof at all */
const RUN_ENV = "BLUEMAP_E2E_DOWNLOAD";
/**
 * The accept-download consent flag, mirroring the core-config option of the same meaning.
 * Setting it asserts that the runner has accepted Mojang's EULA, owns a Minecraft (Java
 * Edition) licence, and agrees to BlueMap downloading a client file from Mojang's servers.
 * `MinecraftVersion#load` documents why it may never be defaulted to true, tests included.
 */
const CONSENT_ENV = "BLUEMAP_ACCEPT_DOWNLOAD";

const LIVE_VERSION = "1.21";
/** gitignored — see design/.gitignore. A Mojang jar is never committed. */
const CLIENT_JAR_CACHE = fileURLToPath(new URL("./.minecraft-client-cache/", import.meta.url));

const runRequested = process.env[RUN_ENV] === "1";
const consentGiven = process.env[CONSENT_ENV] === "1";

/**
 * The skip below only names itself under a reporter that prints individual test-titles;
 * the default one prints a bare "1 skipped". So the reason is also written to stdout at
 * collection-time, before any console-mock is installed — a proof that never ran must not
 * be mistakable for a proof that passed.
 */
if (!runRequested || !consentGiven) {
    console.info(
        `[resourcepack-e2e] Proof 2 (live Minecraft ${LIVE_VERSION} client-jar) DID NOT RUN. ` +
            `It is opt-in: set ${RUN_ENV}=1 and ${CONSENT_ENV}=1 to enable it. ` +
            `Proofs 1 and 3 ran offline as usual.`,
    );
}

/** a client-jar download plus a full vanilla pack load is minutes of work, not seconds */
const LIVE_TIMEOUT_MS = 20 * 60 * 1000;

describe("Proof 2 — a real Minecraft client-jar resolves minecraft:grass_block", () => {
    if (!runRequested || !consentGiven) {
        // A silently-skipped proof is worse than no proof, so the reason is in the title:
        // whoever reads the run output can tell "this passed" from "this never ran".
        it.skip(
            `SKIPPED, NEVER RAN — this proof downloads the real Minecraft ${LIVE_VERSION} client-jar ` +
                `from Mojang. To run it set BOTH ${RUN_ENV}=1 and ${CONSENT_ENV}=1 ` +
                `(${CONSENT_ENV}=1 means you accept Mojang's EULA and own a Minecraft Java Edition ` +
                `licence). Currently ${RUN_ENV}=${process.env[RUN_ENV] ?? "<unset>"}, ` +
                `${CONSENT_ENV}=${process.env[CONSENT_ENV] ?? "<unset>"}. ` +
                `See packages/engine/README.md.`,
            () => {
                // intentionally empty — this body never runs
            },
        );
        return;
    }

    it(
        `downloads the ${LIVE_VERSION} client-jar and resolves grass_block to real texture pixels`,
        async () => {
            await mkdir(CLIENT_JAR_CACHE, { recursive: true });

            // `true` here is the accept-download consent the runner gave via CONSENT_ENV.
            // The jar is cached under CLIENT_JAR_CACHE, so a rerun re-uses it.
            const version = await MinecraftVersion.load(LIVE_VERSION, CLIENT_JAR_CACHE, true);
            expect(version.getId()).toBe(LIVE_VERSION);

            // hand the loader the jar *path* — Pack#loadResourcePath mounts it itself,
            // exactly as it does for a jar the caller configured
            const cacheFs = new DirFileSystem(CLIENT_JAR_CACHE);
            const jar = cacheFs.getRoot().resolve(basename(version.getResourcePack()));
            expect(await jar.isRegularFile()).toBe(true);

            const pack = new ResourcePack(version.getResourcePackVersion());
            await pack.loadResources([jar]);

            const resource = pack.getBlockStates().get(Key.minecraft("grass_block"));
            expect(resource).not.toBeNull();

            const selected = selectAt(
                resource!,
                worldBlock("grass_block", { snowy: "false" }),
                0,
                0,
                0,
            );
            expect(selected.length).toBe(1);
            expect(selected[0]!.getModel().getFormatted()).toContain("grass_block");

            const model = selected[0]!.getModel().getResource((key) => pack.getModels().get(key));
            expect(model).not.toBeNull();
            expect(model!.getElements()).not.toBeNull();

            const faces = model!.getElements()![0]!.getFaces();
            expect(faces.size).toBeGreaterThan(0);

            let resolvedFaces = 0;
            for (const face of faces.values()) {
                const texturePath = face
                    .getTexture()
                    .getTexturePath((name) => model!.getTextures().get(name) ?? null);
                expect(texturePath).not.toBeNull();

                const texture = texturePath!.getResource((key) => pack.getTextures().get(key));
                expect(texture).not.toBeNull();

                // a real vanilla texture, not the bluemap missing-texture placeholder
                expect(texture!.getKey().getNamespace()).toBe(Key.MINECRAFT_NAMESPACE);

                const image = texture!.getTextureImage();
                expect(image.width).toBeGreaterThan(0);
                expect(image.height).toBeGreaterThan(0);
                expect(image.data.length).toBe(image.width * image.height * 4);

                resolvedFaces++;
            }
            expect(resolvedFaces).toBe(faces.size);
        },
        LIVE_TIMEOUT_MS,
    );
});

// #endregion
