import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Key } from "@material-bluemap/shared";
import type { PNG } from "pngjs";
import { TextureGallery } from "../src/map/TextureGallery.js";
import { MinecraftVersion } from "../src/resources/MinecraftVersion.js";
import { VersionManifest } from "../src/resources/VersionManifest.js";
import { parse } from "../src/resources/adapter/JsonMapper.js";
import { PackVersion } from "../src/resources/pack/PackVersion.js";
import { ResourcePack } from "../src/resources/pack/resourcepack/ResourcePack.js";
import type { BlockState as PackBlockState } from "../src/resources/pack/resourcepack/blockstate/BlockState.js";
import type { Variant } from "../src/resources/pack/resourcepack/blockstate/Variant.js";
import { hashToFloat } from "../src/resources/pack/resourcepack/blockstate/VariantSet.js";
import { Model } from "../src/resources/pack/resourcepack/model/Model.js";
import { DirFileSystem } from "../src/resources/pack/vfs/DirFileSystem.js";
import { ZipFileSystem } from "../src/resources/pack/vfs/ZipFileSystem.js";
import { buildZip } from "../src/resources/pack/vfs/zipTestUtil.js";
import { LEGACY_RESOURCES_EXTENSION } from "../src/resources/pack/resourcepack/legacy/LegacyResourcePackExtension.js";
import { flattenLegacyBlockState } from "../src/world/mca/legacy/FlatteningRename.js";
import { Direction } from "../src/util/Direction.js";
import { BlockState as WorldBlockState } from "../src/world/BlockState.js";
import {
    E2E_BLOCK_MODEL_JSON,
    E2E_STONE_BOTTOM_RIGHT,
    E2E_STONE_FIELD,
    E2E_STONE_TOP_LEFT,
    PACK_FORMAT,
    vanillaShapedPackZip,
    type Pixel,
} from "./fixtures/vanillaShapedPack.js";

/*
 * Wave C4-2 — the three end-to-end proofs that close Phase C.
 *
 *   Proof 1  offline; runs on every `pnpm test`. Resolves a block all the way from a
 *            blockstate-json down to real texture pixels over a synthetic, vanilla-shaped
 *            pack, then indexes that pack's textures with a TextureGallery.
 *   Proof 2  the live check against a real Minecraft client-jar. OPT-IN, and skipped by
 *            default — it downloads from Mojang's servers, so it needs both an env-var and
 *            the accept-download consent flag. See packages/engine/README.md.
 *   Proof 3  the shape of the textures.json document, asserted against upstream's
 *            *serialization contract as read from the java source*. It is NOT a comparison
 *            against java output — see the note on that describe-block.
 *
 * Everything these tests read is generated by test/fixtures/vanillaShapedPack.ts, except
 * proof 2, which reads a client-jar the runner downloaded and which is never committed.
 */

// #region shared helpers

/** the rgba pixel at (x, y) of a decoded texture-image */
function pixel(image: PNG, x: number, y: number): Pixel {
    const i = (image.width * y + x) << 2;
    return [image.data[i]!, image.data[i + 1]!, image.data[i + 2]!, image.data[i + 3]!];
}

/** every variant the given resourcepack-blockstate selects for a world-block at (x, y, z) */
function selectAt(
    resource: PackBlockState,
    state: WorldBlockState,
    x: number,
    y: number,
    z: number,
): Variant[] {
    const selected: Variant[] = [];
    resource.forEach(state, x, y, z, (variant) => selected.push(variant));
    return selected;
}

function worldBlock(id: string, properties: Record<string, string> = {}): WorldBlockState {
    return new WorldBlockState(Key.minecraft(id), new Map(Object.entries(properties)));
}

beforeEach(() => {
    // the pack-loader logs its phases through the console (see ResourcePack.ts)
    vi.spyOn(console, "debug").mockImplementation(() => {});
    vi.spyOn(console, "info").mockImplementation(() => {});
    vi.spyOn(console, "warn").mockImplementation(() => {});
});

afterEach(() => {
    vi.restoreAllMocks();
});

// #endregion
// #region proof 1 — the offline resolution chain

/** the fixture pack, mounted from the in-memory jar and fully loaded + baked */
async function loadFixturePack(): Promise<ResourcePack> {
    const fileSystem = await ZipFileSystem.fromBuffer(vanillaShapedPackZip(), "e2e-fixture.jar");
    const pack = new ResourcePack(new PackVersion(PACK_FORMAT, 0));
    await pack.loadResources(fileSystem.getRootDirectories());
    return pack;
}

const E2E_BLOCK = Key.minecraft("e2e_block");
const E2E_STONE_TEXTURE = Key.minecraft("block/e2e_stone");
const E2E_UNUSED_TEXTURE = Key.minecraft("block/e2e_unused");

/**
 * The ordinals `TextureGallery#put(ResourcePool)` has to hand out for the fixture pack:
 * the missing-texture first, then the opaque textures in formatted-key order, then the
 * half-transparent ones in formatted-key order. None of this is the pool's own order —
 * the fixture writes its texture-entries scrambled on purpose.
 */
const EXPECTED_GALLERY_ORDER: readonly string[] = [
    "bluemap:block/missing",
    // opaque (getColorPremultiplied().a === 1)
    "minecraft:block/e2e_amber",
    "minecraft:block/e2e_fallback",
    "minecraft:block/e2e_lamp",
    "minecraft:block/e2e_stone",
    // half-transparent (getColorPremultiplied().a < 1)
    "minecraft:block/e2e_glass",
    "minecraft:block/e2e_water",
];

describe("Proof 1 — a block resolves end-to-end over a synthetic vanilla-shaped pack", () => {
    it("matches a Variants condition, and matches nothing when the condition cannot hold", async () => {
        const pack = await loadFixturePack();

        const resource = pack.getBlockStates().get(E2E_BLOCK);
        expect(resource).not.toBeNull();

        const variants = resource!.getVariants();
        expect(variants).not.toBeNull();
        // the fixture declares no "" / "default" member, so nothing can fall through
        expect(variants!.getDefaultVariant()).toBeNull();
        expect(variants!.getVariants().length).toBe(2);

        // lit=true selects the single-variant set …
        const litSelection = selectAt(resource!, worldBlock("e2e_block", { lit: "true" }), 0, 0, 0);
        expect(litSelection.length).toBe(1);
        expect(litSelection[0]!.getModel().getFormatted()).toBe("minecraft:block/e2e_block_lit");

        // … and a block that carries no `lit` property at all matches neither condition
        expect(selectAt(resource!, worldBlock("e2e_block"), 0, 0, 0)).toEqual([]);
    });

    it("selects a weighted variant by position, deterministically", async () => {
        const pack = await loadFixturePack();
        const resource = pack.getBlockStates().get(E2E_BLOCK)!;
        const unlit = worldBlock("e2e_block", { lit: "false" });

        // the fixture's lit=false set holds weights 1 and 3 (total 4), so
        // VariantSet#forEach picks the first variant exactly when hashToFloat < 0.25
        expect(hashToFloat(0, 0, 0)).toBeLessThan(0.25);
        expect(hashToFloat(0, 0, 1)).toBeGreaterThanOrEqual(0.25);

        const atOrigin = selectAt(resource, unlit, 0, 0, 0);
        expect(atOrigin.length).toBe(1);
        expect(atOrigin[0]!.getModel().getFormatted()).toBe("minecraft:block/e2e_block");

        const atNeighbour = selectAt(resource, unlit, 0, 0, 1);
        expect(atNeighbour.length).toBe(1);
        expect(atNeighbour[0]!.getModel().getFormatted()).toBe("minecraft:block/e2e_block_alt");

        // the same coordinate always yields the same variant — it is a position-hash, not a prng
        expect(selectAt(resource, unlit, 0, 0, 0)[0]).toBe(atOrigin[0]);
        expect(selectAt(resource, unlit, 0, 0, 1)[0]).toBe(atNeighbour[0]);
    });

    it("resolves the selected variant's model through a two-level parent chain", async () => {
        const pack = await loadFixturePack();
        const resource = pack.getBlockStates().get(E2E_BLOCK)!;

        const variant = selectAt(resource, worldBlock("e2e_block", { lit: "false" }), 0, 0, 0)[0]!;
        const model = variant.getModel().getResource((key) => pack.getModels().get(key));
        expect(model).not.toBeNull();

        // applyParent nulls the parent-path as it walks, so a baked model has none left
        expect(model!.getParent()).toBeNull();

        // one level up (block/cube_all): the element and the "particle" variable
        expect(model!.getElements()).not.toBeNull();
        expect(model!.getElements()!.length).toBe(1);
        expect(model!.getTextures().has("particle")).toBe(true);

        // two levels up (block/block): a variable and an ambientocclusion that only the
        // grandparent declares — they can only be here if applyParent recursed
        expect(model!.getTextures().has("fallback_only")).toBe(true);
        expect(model!.isAmbientocclusion()).toBe(false);

        // calculateProperties then found six faces backed by an opaque texture
        expect(model!.isOccluding()).toBe(true);
        expect(model!.isCulling()).toBe(true);
    });

    it("follows the #reference texture-variable indirection to the real texture pixels", async () => {
        const pack = await loadFixturePack();
        const resource = pack.getBlockStates().get(E2E_BLOCK)!;
        const variant = selectAt(resource, worldBlock("e2e_block", { lit: "false" }), 0, 0, 0)[0]!;
        const model = variant.getModel().getResource((key) => pack.getModels().get(key))!;

        // as parsed, "all" really is a reference to "tinted" — the indirection below is
        // not an artefact of the fixture already holding a path
        const asParsed = Model.Adapter.read(parse(E2E_BLOCK_MODEL_JSON));
        const parsedAll = asParsed.getTextures().get("all")!;
        expect(parsedAll.isReference()).toBe(true);
        expect(parsedAll.getReferenceName()).toBe("tinted");
        expect(parsedAll.getTexturePath()).toBeNull();

        // the face names "#all", which has to hop "all" -> "#tinted" -> "tinted"
        const face = model.getElements()![0]!.getFaces().get(Direction.UP);
        expect(face).toBeDefined();

        const texturePath = face!
            .getTexture()
            .getTexturePath((name) => model.getTextures().get(name) ?? null);
        expect(texturePath).not.toBeNull();
        expect(texturePath!.getFormatted()).toBe("minecraft:block/e2e_stone");

        // it is the very ResourcePath object declared under "tinted": resolveTexturePath
        // assigns the referenced variable's own path, so identity proves the hop happened
        expect(texturePath).toBe(model.getTextures().get("tinted")!.getTexturePath());

        const texture = texturePath!.getResource((key) => pack.getTextures().get(key));
        expect(texture).not.toBeNull();
        expect(texture!.getKey().getFormatted()).toBe("minecraft:block/e2e_stone");

        // … and the decoded image is the one the fixture painted, marker pixels and all
        const decoded = texture!.getTextureImage();
        expect([decoded.width, decoded.height]).toEqual([16, 16]);
        expect(pixel(decoded, 0, 0)).toEqual(E2E_STONE_TOP_LEFT);
        expect(pixel(decoded, 15, 15)).toEqual(E2E_STONE_BOTTOM_RIGHT);
        expect(pixel(decoded, 8, 8)).toEqual(E2E_STONE_FIELD);
    });

    it("keeps a texture no model references out of the pool", async () => {
        const pack = await loadFixturePack();

        expect(pack.getTextures().get(E2E_STONE_TEXTURE)).not.toBeNull();
        expect(pack.getTextures().get(E2E_UNUSED_TEXTURE)).toBeNull();
    });
});

describe("Proof 1 — the TextureGallery over that pack", () => {
    it("gives ordinal 0 to bluemap:block/missing, then opaque-first and key-sorted", async () => {
        const pack = await loadFixturePack();

        const gallery = new TextureGallery();
        gallery.put(pack.getTextures());

        const written = JSON.parse(gallery.writeTexturesFile()) as { resourcePath: string }[];
        expect(written.map((texture) => texture.resourcePath)).toEqual(EXPECTED_GALLERY_ORDER);

        // the gallery's own lookup agrees with the document it wrote
        expect(gallery.get(Key.bluemap("block/missing"))).toBe(0);
        EXPECTED_GALLERY_ORDER.forEach((formatted, ordinal) => {
            expect(gallery.get(Key.parse(formatted))).toBe(ordinal);
        });

        // an unknown key falls back to the missing-texture's ordinal
        expect(gallery.get(E2E_UNUSED_TEXTURE)).toBe(0);
    });

    it("preserves every ordinal across a write -> read round trip", async () => {
        const pack = await loadFixturePack();

        const gallery = new TextureGallery();
        gallery.put(pack.getTextures());
        const document = gallery.writeTexturesFile();

        const reread = TextureGallery.readTexturesFile(document);

        EXPECTED_GALLERY_ORDER.forEach((formatted, ordinal) => {
            expect(reread.get(Key.parse(formatted))).toBe(ordinal);
        });

        // re-writing the re-read gallery lands every key back on the same index, which is
        // what a re-loaded resource-pack has to do for already-rendered tiles to keep
        // pointing at the textures they were rendered against
        const rewritten = JSON.parse(reread.writeTexturesFile()) as { resourcePath: string }[];
        expect(rewritten.map((texture) => texture.resourcePath)).toEqual(EXPECTED_GALLERY_ORDER);

        // note: the *animation* member deliberately does not survive the round trip —
        // upstream's writer and reader disagree, which is pinned bug-for-bug by
        // src/resources/pack/resourcepack/texture/Texture.test.ts. Only the ordinals are
        // claimed here.
    });
});

// #endregion
// #region proof 3 — the shape of textures.json

/**
 * Upstream's serialization contract for `textures.json`, read from the java source at
 * vendor/BlueMap (tag-free `main` tree, commit e664c1a):
 *
 *   core/…/map/TextureGallery.java
 *     - `GSON.toJson(textures, Texture[].class, writer)` — a BARE ARRAY indexed by ordinal,
 *       built with `ResourcesGson.addAdapter(new GsonBuilder())` plus
 *       `FieldNamingPolicy.IDENTITY`, so member-names are the java field-names verbatim.
 *   core/…/resources/pack/resourcepack/texture/Texture.java
 *     - `@SerializedName("resourcePath") private Key key` — the member is `resourcePath`,
 *       NOT `key`.
 *     - `private Color color`, `private boolean halfTransparent`, `private String texture`.
 *     - `@Nullable private AnimationMeta animation` — gson does not serialize nulls by
 *       default, so the member is OMITTED when there is no animation.
 *     - the texture-string is `TEXTURE_STRING_PREFIX + base64`, i.e. `data:image/png;base64,…`.
 *   core/…/resources/adapter/ColorAdapter.java
 *     - `write` calls `value.straight()` then emits `[r, g, b, a]` — a four-number array.
 *
 * THIS IS A SHAPE ASSERTION, NOT A DIFF AGAINST JAVA. No java output has been generated or
 * compared; there is no oracle yet (that is issue #3). Do not read a passing run here as
 * "matches BlueMap" — it says only that the document has the members upstream's gson would
 * emit, with the types it would emit them as.
 *
 * WHEN THE ORACLE LANDS: keep this block (a shape failure is a clearer diagnosis than a
 * byte diff) and add a sibling test that loads the java-produced `textures.json` for the
 * same pack and compares parsed element-for-element — resourcePath and ordinal exactly,
 * color within a float32 epsilon, and the decoded png pixel-for-pixel rather than by
 * base64 string, since two png encoders may disagree on chunk layout for identical pixels.
 */
describe("Proof 3 — textures.json has the shape upstream's gson would emit", () => {
    const TEXTURE_URI_PREFIX = "data:image/png;base64,";

    async function texturesJson(): Promise<unknown> {
        const pack = await loadFixturePack();
        const gallery = new TextureGallery();
        gallery.put(pack.getTextures());
        return JSON.parse(gallery.writeTexturesFile());
    }

    it("is a bare array indexed by ordinal, not an object", async () => {
        const document = await texturesJson();

        expect(Array.isArray(document)).toBe(true);
        expect((document as unknown[]).length).toBe(EXPECTED_GALLERY_ORDER.length);
    });

    it("carries resourcePath / color / halfTransparent / texture on every element", async () => {
        const elements = (await texturesJson()) as Record<string, unknown>[];

        for (const element of elements) {
            const members = Object.keys(element).sort();
            // `animation` is the only optional member; nothing else may appear
            expect(members.filter((name) => name !== "animation")).toEqual([
                "color",
                "halfTransparent",
                "resourcePath",
                "texture",
            ]);

            // the java field is `key`; the wire member is `resourcePath`
            expect(element["key"]).toBeUndefined();
            expect(typeof element["resourcePath"]).toBe("string");
            expect(Key.parse(element["resourcePath"] as string).getFormatted()).toBe(
                element["resourcePath"],
            );

            // ColorAdapter#write -> [r, g, b, a]. Four finite numbers is the whole
            // contract — gson writes raw floats, so no range is promised (and asserting
            // one would be a float-epsilon flake on a straight()-divided average).
            const color = element["color"];
            expect(Array.isArray(color)).toBe(true);
            expect((color as unknown[]).length).toBe(4);
            for (const channel of color as unknown[]) {
                expect(typeof channel).toBe("number");
                expect(Number.isFinite(channel as number)).toBe(true);
                expect(channel as number).toBeGreaterThanOrEqual(0);
            }

            expect(typeof element["halfTransparent"]).toBe("boolean");
            expect(typeof element["texture"]).toBe("string");
            expect(element["texture"] as string).toMatch(/^data:image\/png;base64,/);
        }
    });

    it("encodes the texture as a decodable data:image/png;base64 uri", async () => {
        const elements = (await texturesJson()) as Record<string, unknown>[];

        const stone = elements.find(
            (element) => element["resourcePath"] === "minecraft:block/e2e_stone",
        );
        expect(stone).toBeDefined();

        const uri = stone!["texture"] as string;
        const base64 = uri.substring(TEXTURE_URI_PREFIX.length);
        const bytes = Buffer.from(base64, "base64");
        // the png signature — the uri really holds png bytes, not an opaque blob
        expect([...bytes.subarray(0, 8)]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    });

    it("omits `animation` when there is none, and emits it when there is", async () => {
        const elements = (await texturesJson()) as Record<string, unknown>[];

        const stone = elements.find(
            (element) => element["resourcePath"] === "minecraft:block/e2e_stone",
        )!;
        expect("animation" in stone).toBe(false);

        // the fixture gives block/e2e_lamp a sibling .png.mcmeta
        const lamp = elements.find(
            (element) => element["resourcePath"] === "minecraft:block/e2e_lamp",
        )!;
        expect("animation" in lamp).toBe(true);
        expect(lamp["animation"]).toEqual({
            interpolate: true,
            width: 1,
            height: 1,
            frametime: 3,
        });
    });
});

// #endregion
// #region proof 2 — the live client-jar check (opt-in; skipped by default)

/** set to `1` to run the live proof at all */
const RUN_ENV = "BLUEMAP_E2E_DOWNLOAD";
/**
 * The accept-download consent flag, mirroring the core-config option of the same meaning.
 * Setting it asserts that the runner has accepted Mojang's EULA, owns a Minecraft (Java
 * Edition) licence, and agrees to BlueMap downloading a client file from Mojang's servers.
 * `MinecraftVersion#load` documents why it may never be defaulted to true, tests included.
 */
const CONSENT_ENV = "BLUEMAP_ACCEPT_DOWNLOAD";

const LIVE_VERSION = "1.21";
/** gitignored — see design/.gitignore. A Mojang jar is never committed. */
const CLIENT_JAR_CACHE = fileURLToPath(new URL("./.minecraft-client-cache/", import.meta.url));

const runRequested = process.env[RUN_ENV] === "1";
const consentGiven = process.env[CONSENT_ENV] === "1";

/**
 * The skip below only names itself under a reporter that prints individual test-titles;
 * the default one prints a bare "1 skipped". So the reason is also written to stdout at
 * collection-time, before any console-mock is installed — a proof that never ran must not
 * be mistakable for a proof that passed.
 */
if (!runRequested || !consentGiven) {
    console.info(
        `[resourcepack-e2e] Proof 2 (live Minecraft ${LIVE_VERSION} client-jar) DID NOT RUN. ` +
            `It is opt-in: set ${RUN_ENV}=1 and ${CONSENT_ENV}=1 to enable it. ` +
            `Proofs 1 and 3 ran offline as usual.`,
    );
}

/** a client-jar download plus a full vanilla pack load is minutes of work, not seconds */
const LIVE_TIMEOUT_MS = 20 * 60 * 1000;

describe("Proof 2 — a real Minecraft client-jar resolves minecraft:grass_block", () => {
    if (!runRequested || !consentGiven) {
        // A silently-skipped proof is worse than no proof, so the reason is in the title:
        // whoever reads the run output can tell "this passed" from "this never ran".
        it.skip(
            `SKIPPED, NEVER RAN — this proof downloads the real Minecraft ${LIVE_VERSION} client-jar ` +
                `from Mojang. To run it set BOTH ${RUN_ENV}=1 and ${CONSENT_ENV}=1 ` +
                `(${CONSENT_ENV}=1 means you accept Mojang's EULA and own a Minecraft Java Edition ` +
                `licence). Currently ${RUN_ENV}=${process.env[RUN_ENV] ?? "<unset>"}, ` +
                `${CONSENT_ENV}=${process.env[CONSENT_ENV] ?? "<unset>"}. ` +
                `See packages/engine/README.md.`,
            () => {
                // intentionally empty — this body never runs
            },
        );
        return;
    }

    it(
        `downloads the ${LIVE_VERSION} client-jar and resolves grass_block to real texture pixels`,
        async () => {
            await mkdir(CLIENT_JAR_CACHE, { recursive: true });

            // `true` here is the accept-download consent the runner gave via CONSENT_ENV.
            // The jar is cached under CLIENT_JAR_CACHE, so a rerun re-uses it.
            const version = await MinecraftVersion.load(LIVE_VERSION, CLIENT_JAR_CACHE, true);
            expect(version.getId()).toBe(LIVE_VERSION);

            // hand the loader the jar *path* — Pack#loadResourcePath mounts it itself,
            // exactly as it does for a jar the caller configured
            const cacheFs = new DirFileSystem(CLIENT_JAR_CACHE);
            const jar = cacheFs.getRoot().resolve(basename(version.getResourcePack()));
            expect(await jar.isRegularFile()).toBe(true);

            const pack = new ResourcePack(version.getResourcePackVersion());
            await pack.loadResources([jar]);

            const resource = pack.getBlockStates().get(Key.minecraft("grass_block"));
            expect(resource).not.toBeNull();

            const selected = selectAt(
                resource!,
                worldBlock("grass_block", { snowy: "false" }),
                0,
                0,
                0,
            );
            expect(selected.length).toBe(1);
            expect(selected[0]!.getModel().getFormatted()).toContain("grass_block");

            const model = selected[0]!.getModel().getResource((key) => pack.getModels().get(key));
            expect(model).not.toBeNull();
            expect(model!.getElements()).not.toBeNull();

            const faces = model!.getElements()![0]!.getFaces();
            expect(faces.size).toBeGreaterThan(0);

            let resolvedFaces = 0;
            for (const face of faces.values()) {
                const texturePath = face
                    .getTexture()
                    .getTexturePath((name) => model!.getTextures().get(name) ?? null);
                expect(texturePath).not.toBeNull();

                const texture = texturePath!.getResource((key) => pack.getTextures().get(key));
                expect(texture).not.toBeNull();

                // a real vanilla texture, not the bluemap missing-texture placeholder
                expect(texture!.getKey().getNamespace()).toBe(Key.MINECRAFT_NAMESPACE);

                const image = texture!.getTextureImage();
                expect(image.width).toBeGreaterThan(0);
                expect(image.height).toBeGreaterThan(0);
                expect(image.data.length).toBe(image.width * image.height * 4);

                resolvedFaces++;
            }
            expect(resolvedFaces).toBe(faces.size);
        },
        LIVE_TIMEOUT_MS,
    );
});

// #endregion
// #region proof 4 — a real 1.12.2 client-jar through the legacy compat path (opt-in)

/**
 * Issue #31, check 2. Shares Proof 2's consent gate (`RUN_ENV`/`CONSENT_ENV`) rather than a
 * separate pair — it is the same category of thing ("downloads a real client-jar from
 * Mojang"), and asking a runner to set two different env-var pairs for the same kind of
 * consent would be a second thing to get wrong for no safety benefit.
 */
const LEGACY_VERSION = "1.12.2";
/** gitignored — see design/.gitignore. A Mojang jar is never committed. */
const LEGACY_CLIENT_JAR_CACHE = fileURLToPath(
    new URL("./.minecraft-client-cache-legacy/", import.meta.url),
);

if (!runRequested || !consentGiven) {
    console.info(
        `[resourcepack-e2e] Proof 4 (live Minecraft ${LEGACY_VERSION} client-jar, legacy ` +
            `compat path) DID NOT RUN. It is opt-in: set ${RUN_ENV}=1 and ${CONSENT_ENV}=1 ` +
            `to enable it.`,
    );
}

describe("Proof 4 — a real 1.12.2 client-jar loads through LegacyResourcePackExtension", () => {
    if (!runRequested || !consentGiven) {
        it.skip(
            `SKIPPED, NEVER RAN — this proof downloads the real Minecraft ${LEGACY_VERSION} ` +
                `client-jar from Mojang. To run it set BOTH ${RUN_ENV}=1 and ${CONSENT_ENV}=1 ` +
                `(${CONSENT_ENV}=1 means you accept Mojang's EULA and own a Minecraft Java ` +
                `Edition licence). Currently ${RUN_ENV}=${process.env[RUN_ENV] ?? "<unset>"}, ` +
                `${CONSENT_ENV}=${process.env[CONSENT_ENV] ?? "<unset>"}. ` +
                `See packages/engine/README.md.`,
            () => {
                // intentionally empty — this body never runs
            },
        );
        return;
    }

    it(
        `downloads the ${LEGACY_VERSION} client-jar and resolves pre-flattening names`,
        async () => {
            await mkdir(LEGACY_CLIENT_JAR_CACHE, { recursive: true });

            /*
             * NOT `MinecraftVersion.load(LEGACY_VERSION, ...)` — that was tried first and it
             * does not download a 1.12.2 jar at all. `MinecraftVersion.load` (faithfully
             * porting the MODERN `MinecraftVersion.java`) clamps any requested id older than
             * `EARLIEST_RESOURCEPACK_VERSION` ("1.13") up to that earliest version — so asking
             * it for "1.12.2" silently hands back a **1.13** jar (pack_format 4, already
             * flattened) instead. That is correct, faithful behaviour for upstream's *modern*
             * pipeline (v5.22 never resolves a resource-pack older than 1.13 that way — real
             * pre-flattening support was a separate branch, v0.10.3-mc1.12, that this port's
             * `LegacyResourcePackExtension` reads models the way *that* branch did), but it
             * means the modern accept-download flow this app actually ships is not the vehicle
             * for obtaining a genuine 1.12.2 jar, which is exactly what this proof needs.
             *
             * So this downloads directly from the version manifest instead — same consent
             * gate, same SHA-1 verification against the manifest's declared digest, same
             * `VersionManifest`/`Version`/`Download` classes `MinecraftVersion.load` itself
             * uses internally, just without the "clamp to 1.13" business rule that only makes
             * sense for the modern render path.
             */
            const manifest = await VersionManifest.getOrFetch();
            const version = manifest.getVersion(LEGACY_VERSION);
            const detail = await version.fetchDetail();
            const download = detail.getDownloads().getClient();

            const jarPath = join(LEGACY_CLIENT_JAR_CACHE, `minecraft-client-${LEGACY_VERSION}.jar`);
            const digest = createHash("sha1");
            const chunks: Buffer[] = [];
            for await (const chunk of await download.createInputStream()) {
                digest.update(chunk);
                chunks.push(Buffer.from(chunk));
            }
            const actualSha1 = digest.digest("hex");
            // verified BEFORE the file is trusted or used for anything, same order
            // `MinecraftVersion.ts`'s own `download()` enforces
            expect(actualSha1).toBe(download.getSha1());
            await writeFile(jarPath, Buffer.concat(chunks));

            const cacheFs = new DirFileSystem(LEGACY_CLIENT_JAR_CACHE);
            const jar = cacheFs.getRoot().resolve(basename(jarPath));
            expect(await jar.isRegularFile()).toBe(true);

            /*
             * pack_format 3 (1.11–1.12.2), per LegacyPackFormat.ts's table — NOT read from
             * the jar, because **a real Minecraft client jar carries no `pack.mcmeta` at
             * all**. Checked directly: neither this 1.12.2 jar, nor the 1.21 jar Proof 2
             * downloads, nor 26.2 (`tools/oracle/out/gate/bluemap-data/`) has one — `jar tf`
             * on all three lists `pack.png` (the pack icon) but never `pack.mcmeta`. That
             * file is how a *user-authored or user-downloaded resource pack* declares its
             * format; the game's own bundled assets apparently never needed to declare a
             * format to themselves, at any era this project has a jar for.
             */
            const jarZip = await ZipFileSystem.openFile(jarPath);
            let jarHasPackMcmeta: boolean;
            try {
                jarHasPackMcmeta = await jarZip.getRootDirectories()[0]!.resolve("pack.mcmeta").exists();
            } finally {
                await jarZip.close();
            }
            expect(
                jarHasPackMcmeta,
                "a real Minecraft client jar does not carry pack.mcmeta — see this block's comment",
            ).toBe(false);

            const bareJarPack = new ResourcePack(new PackVersion(3, 0));
            await bareJarPack.loadResources([jar]);

            /*
             * THE FINDING: `LegacyResourcePackExtension.isLegacy()` is gated entirely on
             * `isLegacyPackRoot`, which reads `pack.mcmeta`'s `pack_format`
             * (`LegacyPackFormat.ts`). Since the real client jar has no `pack.mcmeta` (just
             * proven above), `isLegacyPackMeta` never sees a pre-flattening format — its own
             * doc comment says a pack that declares no format "reads as modern" by design,
             * specifically so a malformed-or-missing `pack.mcmeta` does not accidentally
             * switch on the compat layer. So loading a BARE 1.12.2 client jar alone does
             * NOT detect as legacy — this is asserted as `false`, not `true`, because that
             * is what actually happens, and asserting the hoped-for answer here would hide
             * exactly the gap issue #31 asked this proof to find.
             *
             * `LegacyResourcePackExtension.test.ts`'s own fixtures only ever exercised the
             * `true` branch because they hand-write a `pack.mcmeta` into their synthetic
             * pack — which a real client jar never has. The extension's unit coverage is
             * real and correct for what it tests; what it never tested is what a real
             * client jar actually looks like.
             */
            const bareJarExtension = bareJarPack.getExtension(LEGACY_RESOURCES_EXTENSION);
            expect(bareJarExtension).not.toBeNull();
            expect(bareJarExtension!.isLegacy()).toBe(false);

            /*
             * So: is the legacy compat path reachable with a real jar at all? Yes — the
             * missing piece is exactly one file, `pack.mcmeta`, which BlueMap's own `packs/`
             * folder mechanism exists to supply alongside a plain client jar (the same
             * mechanism `resourceExtensions.zip` uses to layer bluemap's own assets on top
             * of vanilla). This builds the smallest possible stand-in: a synthetic root
             * containing *only* `pack.mcmeta` declaring `pack_format: 3`, mounted ahead of
             * the real jar. It contributes no textures or models of its own — every asset
             * below still comes from the genuine 1.12.2 jar — it only supplies the one
             * signal `isLegacyPackRoot` needs.
             */
            const legacyManifestOnly = await ZipFileSystem.fromBuffer(
                buildZip([
                    { name: "pack.mcmeta", data: JSON.stringify({ pack: { pack_format: 3 } }) },
                ]),
                "legacy-manifest-only.zip",
            );

            const pack = new ResourcePack(new PackVersion(3, 0));
            await pack.loadResources([...legacyManifestOnly.getRootDirectories(), jar]);

            const legacyExtension = pack.getExtension(LEGACY_RESOURCES_EXTENSION);
            expect(legacyExtension).not.toBeNull();
            expect(
                legacyExtension!.isLegacy(),
                "with the synthetic pack.mcmeta supplied, the real jar's blockstates/models " +
                    "should now go through the legacy compat path",
            ).toBe(true);

            /**
             * Five pre-flattening blockstates, chosen to exercise everything
             * LegacyResourcePackExtension does:
             *
             *  - "stone" / "dirt" / "oak_planks": each 1.12 blockstate names its model bare
             *    ("stone", not "minecraft:block/stone") — proves `remapBlockModelReferences`.
             *    ("oak_planks" replaces an originally-planned single "planks" blockstate
             *    keyed on a `variant` property — checked directly against the real jar: 1.12.2
             *    already splits wood species into separate per-species blockstate files
             *    (`oak_planks.json`, `birch_planks.json`, ...), same as the modern pack. The
             *    world-save format is what stayed unified as one numeric id with a species
             *    metadata nibble until the 1.13 flattening; the resource-pack side had
             *    already split it. `BlockIdMapper`/`blockIds.json` is what bridges the two.)
             *  - "stone" additionally exercises `Variants.Adapter`'s pre-flattening "normal"
             *    condition spelling resolving to an unconditional multi-option variant list
             *    (four rotations of the same two models) — not just a single bare variant.
             *  - "grass": era-correct here. Against a MODERN pack this exact name means the
             *    grass tuft (the documented gap in design/HANDOFF.md and
             *    tools/oracle/render-1-12.mjs's KNOWN_LEGACY_RENDER_GAPS) — against the real
             *    1.12.2 pack it is the grass BLOCK, which is what this asserts.
             *  - "snow_layer": the flattening removed this name entirely, so a modern pack
             *    has no blockstate for it at all — the era-matched pack does.
             *
             * Each is asserted through to a real, non-missing, non-empty texture image —
             * not just "a model was found" — because `remapBlockModelReferences` caching a
             * resource onto the wrong path would still let `getResource()` return non-null.
             */
            const legacyBlocks: { id: string; properties?: Record<string, string> }[] = [
                { id: "stone" },
                { id: "dirt" },
                { id: "oak_planks" },
                // "grass" already keys on `snowy` in the REAL 1.12.2 pack — checked directly
                // against the jar (assets/minecraft/blockstates/grass.json:
                // "snowy=false"/"snowy=true"). `snowy` is supplied here the same way
                // `SnowyExtension` (packages/engine/src/world/mca/legacy/extensions/) derives
                // it when reading a real legacy chunk, since this test builds the
                // world-BlockState directly rather than through a chunk reader.
                { id: "grass", properties: { snowy: "false" } },
                // "snow_layer" keys on `layers` (1-8) — checked directly against the jar too.
                { id: "snow_layer", properties: { layers: "1" } },
            ];

            for (const { id, properties } of legacyBlocks) {
                const resource = pack.getBlockStates().get(Key.minecraft(id));
                expect(resource, `blockstate '${id}' should be defined by the 1.12.2 pack`).not.toBeNull();

                const selected = selectAt(resource!, worldBlock(id, properties), 0, 0, 0);
                expect(selected.length, `'${id}' should select exactly one variant`).toBe(1);

                const model = selected[0]!.getModel().getResource((key) => pack.getModels().get(key));
                expect(model, `'${id}' should resolve to a real model, not fall through to null`)
                    .not.toBeNull();
                expect(model!.getElements(), `'${id}' should have geometry`).not.toBeNull();

                const faces = model!.getElements()![0]!.getFaces();
                expect(faces.size, `'${id}' should have at least one face`).toBeGreaterThan(0);

                for (const face of faces.values()) {
                    const texturePath = face
                        .getTexture()
                        .getTexturePath((name) => model!.getTextures().get(name) ?? null);
                    expect(texturePath, `'${id}' should resolve every face's texture variable`)
                        .not.toBeNull();

                    const texture = texturePath!.getResource((key) => pack.getTextures().get(key));
                    expect(texture, `'${id}' should resolve to a real texture resource`).not.toBeNull();
                    // a real vanilla texture, not bluemap's own missing-texture placeholder
                    expect(texture!.getKey().getNamespace()).toBe(Key.MINECRAFT_NAMESPACE);

                    const image = texture!.getTextureImage();
                    expect(image.width).toBeGreaterThan(0);
                    expect(image.height).toBeGreaterThan(0);
                }
            }

            /*
             * The other half of issue #31's check 2: "note how the era-matched path
             * interacts with [the flattening rename table]". `grass` just resolved
             * perfectly above, looked up DIRECTLY. But nothing in the render path looks it
             * up directly — `BlockStateModelRenderer.ts` runs every block through
             * `flattenLegacyBlockState` first whenever `block.isLegacy()` is true (gated on
             * the WORLD chunk's era, not on which pack is loaded), unconditionally, so this
             * reproduces exactly that call against the SAME era-matched `pack` used above.
             */
            const renamed = flattenLegacyBlockState(worldBlock("grass", { snowy: "false" }));
            // the table renames it to "minecraft:grass_block" — a name that did not exist
            // before the 1.13 flattening, so the era-matched (pre-flattening) pack has never
            // heard of it
            expect(renamed.getId().getFormatted()).toBe("minecraft:grass_block");

            const renamedResource = pack.getBlockStates().get(renamed.getId());
            /*
             * THE FINDING: this is null. `flattenLegacyBlockState` is correct and necessary
             * against the MODERN pack (it is the fix `render-1-12.mjs`'s now-empty
             * `KNOWN_LEGACY_RENDER_GAPS` records), but firing it unconditionally — gated on
             * the world's era rather than the resource pack's — means an era-matched render
             * takes a name the pack already resolves correctly (proven above: bare "grass"
             * has a real model and real texture in this exact pack) and rewrites it into one
             * the pack has never heard of, right before the only lookup that matters.
             * `BlockStateModelRenderer.ts` then does `if (stateResource == null) return;` —
             * the block is not drawn with a missing-texture placeholder, it is skipped
             * entirely, silently. `tools/oracle/render-1-12-era-matched.mjs`'s real render of
             * this exact seed shows the matching symptom: no grass-family texture anywhere
             * in the gallery, and `minecraft:blocks/dirt` at 72,258 vertices — the same "the
             * ground is no longer occluded from above" signature design/HANDOFF.md recorded
             * for the ORIGINAL modern-pack bug this table was written to fix.
             */
            expect(
                renamedResource,
                "flattenLegacyBlockState's output should NOT resolve in the era-matched " +
                    "pack (it renamed an already-correct name into one that never existed " +
                    "pre-flattening) — if this is no longer null, the interaction bug " +
                    "described in this test has been fixed and this assertion should flip",
            ).toBeNull();
        },
        LIVE_TIMEOUT_MS,
    );
});

// #endregion
