/**
 * `core.conf` — the settings that apply to the whole of BlueMap.
 *
 * Java source: `common/src/main/java/de/bluecolored/bluemap/common/config/CoreConfig.java`
 * Template:    `common/src/main/resources/de/bluecolored/bluemap/config/core.conf`
 */

import { z } from "zod";
import type { FieldMeta, GroupMeta } from "../meta.js";
import { CORE_TEMPLATE } from "../templates/sources.js";
import { hoconBoolean, hoconInt, hoconString, integerControl, sliderControl, SWITCH } from "./common.js";
import type { ConfigFileDescriptor } from "./descriptor.js";

export const coreConfigSchema = z.object({
    "accept-download": hoconBoolean().default(false),
    data: hoconString().default("bluemap"),
    "render-thread-count": hoconInt().default(1),
    "render-thread-priority": hoconInt({ min: 1, max: 10 }).default(5),
    "update-cooldown": hoconInt().default(60),
    "full-update-interval": hoconInt().default(1440),
    "scan-for-mod-resources": hoconBoolean().default(true),
    metrics: hoconBoolean().default(true),
    log: z
        .object({
            file: hoconString().nullable().default(null),
            append: hoconBoolean().default(false),
        })
        .default({ file: null, append: false }),
});

export type CoreConfig = z.infer<typeof coreConfigSchema>;

const GROUPS: readonly GroupMeta[] = [
    {
        id: "consent",
        label: "Minecraft client download",
        description: "BlueMap textures the map from the real Minecraft client jar, so it cannot render anything until this is accepted.",
    },
    { id: "paths", label: "Folders" },
    { id: "performance", label: "Render threads" },
    { id: "updates", label: "Update timing" },
    { id: "resources", label: "Resources" },
    { id: "privacy", label: "Metrics" },
    { id: "logging", label: "Debug log" },
];

const FIELDS: readonly FieldMeta[] = [
    {
        path: "accept-download",
        key: "accept-download",
        segments: ["accept-download"],
        javaField: "acceptDownload",
        label: "Accept the Minecraft client download",
        doc: [
            "By changing the setting (accept-download) below to TRUE you are indicating that you have accepted Mojang's EULA (https://account.mojang.com/documents/minecraft_eula),",
            "you confirm that you own a license to Minecraft (Java Edition),",
            "and you agree that BlueMap will download and use a Minecraft client file (depending on the Minecraft version) from Mojang's servers (https://piston-meta.mojang.com/) for you.",
            "This file contains resources that belong to Mojang and you must not redistribute it or do anything else that is not compliant with Mojang's EULA.",
            "BlueMap uses resources in this file to generate the 3D models used for the map and texture them. Without these, BlueMap will not work.",
        ].join("\n"),
        group: "consent",
        control: SWITCH,
        default: false,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
        consentGated: true,
    },
    {
        path: "data",
        key: "data",
        segments: ["data"],
        javaField: "data",
        label: "Data folder",
        doc: [
            "The folder where BlueMap saves data files it needs during runtime.",
            "For example, the render progress file, which is used to resume the render across restarts.",
            'Default is "bluemap"',
        ].join("\n"),
        group: "paths",
        control: { kind: "path", select: "directory", relativeToWorkingDirectory: true },
        default: "bluemap",
        templateValue: { value: "data", note: "The CLI passes 'data' as its default data folder, so a generated core.conf says data rather than bluemap." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "render-thread-count",
        key: "render-thread-count",
        segments: ["render-thread-count"],
        javaField: "renderThreadCount",
        label: "Render threads",
        doc: [
            "This changes the amount of threads that BlueMap will use to render the maps.",
            "A higher value can improve the render speed, but could impact performance on the host machine.",
            "This should be always below or equal to the number of available processor cores.",
            "Zero or a negative value means the amount of available processor cores subtracted by the value.",
            "For example, on a machine with 6 cores, a value of -2 would result in 4 render threads.",
            "Default is 1",
        ].join("\n"),
        group: "performance",
        control: integerControl({ step: 1, unit: "threads" }),
        default: 1,
        templateValue: {
            value: 1,
            note: "The generated file carries a suggestion based on the machine: 1, or 2 with at least 6 cores and 4 GiB of heap, or 3 with at least 10 cores and 8 GiB.",
        },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "render-thread-priority",
        key: "render-thread-priority",
        segments: ["render-thread-priority"],
        javaField: "renderThreadPriority",
        label: "Render thread priority",
        doc: [
            "This changes the priority that BlueMap's render-threads will get.",
            "How the thread-priority affects actual performance depends on your JVM.",
            "The priority must be a value between 1 and 10.",
            "Default is Javas default priority (5)",
        ].join("\n"),
        group: "performance",
        control: sliderControl({ min: 1, max: 10, step: 1, integer: true }),
        default: 5,
        commentedOutInTemplate: true,
        hidden: false,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "update-cooldown",
        key: "update-cooldown",
        segments: ["update-cooldown"],
        javaField: "updateCooldown",
        label: "Region update cooldown",
        doc: [
            "Cooldown time in seconds for updating region-files.",
            "Only when the -u flag is used.",
            "If a region-file got updated once, the same region-file will not be updated again until this cooldown-time has passed.",
            "Default is 60 seconds",
        ].join("\n"),
        group: "updates",
        control: integerControl({ min: 0, step: 1, unit: "seconds" }),
        default: 60,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "full-update-interval",
        key: "full-update-interval",
        segments: ["full-update-interval"],
        javaField: "fullUpdateInterval",
        label: "Full update interval",
        doc: [
            "The interval in minutes at which a full map update will be triggered.",
            "Only when the -u flag is used.",
            "This is IN ADDITION to the normal map update process (in case that fails to detect any file changes).",
            "! This DOESN'T re-render the entire map each time, it only checks if there are some changes that have not been rendered yet!",
            "Set to 0 to disable.",
            "Default is 1440 (24 hours)",
        ].join("\n"),
        group: "updates",
        control: integerControl({ min: 0, step: 1, unit: "minutes" }),
        default: 1440,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "scan-for-mod-resources",
        key: "scan-for-mod-resources",
        segments: ["scan-for-mod-resources"],
        javaField: "scanForModResources",
        label: "Scan for mod resources and datapacks",
        doc: [
            "Controls whether BlueMap should try to find and load mod resources and datapacks from the server/world directories.",
            "Default is true",
        ].join("\n"),
        group: "resources",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Not stated upstream, but loading or dropping a resource pack changes how blocks are textured, so existing tiles no longer match.",
        advanced: false,
    },
    {
        path: "metrics",
        key: "metrics",
        segments: ["metrics"],
        javaField: "metrics",
        label: "Send anonymous usage metrics",
        doc: [
            "If this is true, BlueMap might send really basic metric reports containing only the implementation type and the version that is being used to https://metrics.bluecolored.de/bluemap/",
            "This allows me to track the basic usage of BlueMap and helps me stay motivated to further develop this tool! Please leave it on :)",
            'An example report looks like this: {"implementation":"cli","version":"5.22-27","mcVersion":"1.21.4"}',
            "Default is true",
        ].join("\n"),
        group: "privacy",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "log.file",
        key: "file",
        segments: ["log", "file"],
        javaField: "log.file",
        label: "Debug log file",
        doc: [
            "The file where the debug log will be written to.",
            "Comment out to disable debug logging completely.",
            "Java String formatting syntax can be used to add timestamps, see: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html",
            "Default is no logging.",
        ].join("\n"),
        group: "logging",
        control: { kind: "path", select: "file", extensions: ["log"], relativeToWorkingDirectory: true },
        default: null,
        templateValue: { value: "data/logs/debug.log", note: "The generated file points at a log inside the data folder, so a fresh install logs by default." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "log.append",
        key: "append",
        segments: ["log", "append"],
        javaField: "log.append",
        label: "Append to the log file",
        doc: ["Whether the logger should append to an existing file, or overwrite it.", "Default is false (overwrite the file)."].join("\n"),
        group: "logging",
        control: SWITCH,
        default: false,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
];

export const coreConfigDescriptor: ConfigFileDescriptor<CoreConfig> = {
    id: "core",
    title: "Core",
    description: "Settings that apply to every map: the Minecraft client download, folders, render threads and logging.",
    location: { pattern: "core.conf", cardinality: "single" },
    schema: coreConfigSchema,
    fields: FIELDS,
    groups: GROUPS,
    legacyKeys: [],
    template: CORE_TEMPLATE,
};
