/**
 * `maps/<id>.conf` — one file per map, and the file most worth getting right.
 *
 * This is where every setting that can invalidate an already-rendered map lives,
 * which is why each field carries {@link FieldMeta.invalidatesTiles}: the GUI has
 * to be able to say "saving this throws away 961 tiles and re-renders them"
 * before somebody clicks save, not afterwards.
 *
 * Java source: `common/src/main/java/de/bluecolored/bluemap/common/config/MapConfig.java`
 * Template:    `common/src/main/resources/de/bluecolored/bluemap/config/maps/map.conf`
 */

import { z } from "zod";
import type { FieldMeta, GroupMeta, LegacyKey } from "../meta.js";
import { MAP_TEMPLATE } from "../templates/sources.js";
import {
    DIMENSION_OPTIONS,
    DIMENSION_TYPE_OPTIONS,
    hexColor,
    hoconBoolean,
    hoconInt,
    hoconNumber,
    hoconString,
    integerControl,
    namespacedKey,
    sliderControl,
    SWITCH,
    vector2i,
    WORLD_LOADER_OPTIONS,
} from "./common.js";
import type { ConfigFileDescriptor } from "./descriptor.js";
import { combinedMaskSchema } from "./mask.js";

/**
 * A marker set as BlueMap's API deserialises it.
 *
 * The set's own container fields are modelled; the markers inside it are passed
 * through untouched. Marker shapes are the markers contract's business, not the
 * config schema's, and half-modelling them here would produce an editor that
 * silently drops fields it did not know about.
 */
const markerSetSchema = z.looseObject({
    label: hoconString().default(""),
    toggleable: hoconBoolean().default(true),
    "default-hidden": hoconBoolean().default(false),
    sorting: hoconInt().default(0),
    markers: z.record(z.string(), z.unknown()).default({}),
});

export const mapConfigSchema = z.object({
    loader: namespacedKey().default("bluemap:anvil"),
    world: hoconString().nullable().default(null),
    dimension: namespacedKey().nullable().default(null),
    "dimension-type": namespacedKey().nullable().default(null),
    name: hoconString().nullable().default(null),
    sorting: hoconInt().default(0),
    "start-pos": vector2i().default({ x: 0, z: 0 }),
    "sky-color": hexColor().default("#7dabff"),
    "void-color": hexColor().default("#000000"),
    "sky-light": hoconNumber().default(1),
    "ambient-light": hoconNumber().default(0),
    "remove-caves-below-y": hoconInt().default(55),
    "cave-detection-ocean-floor": hoconInt().default(10000),
    "cave-detection-uses-block-light": hoconBoolean().default(false),
    "min-inhabited-time": hoconInt().default(0),
    "min-inhabited-time-radius": hoconInt().default(0),
    "render-mask": combinedMaskSchema.default([]),
    "render-edges": hoconBoolean().default(true),
    "edge-light-strength": hoconInt().default(15),
    "enable-perspective-view": hoconBoolean().default(true),
    "enable-flat-view": hoconBoolean().default(true),
    "enable-free-flight-view": hoconBoolean().default(true),
    "enable-hires": hoconBoolean().default(true),
    "check-for-removed-regions": hoconBoolean().default(true),
    storage: hoconString().default("file"),
    "ignore-missing-light-data": hoconBoolean().default(false),
    "marker-sets": z.record(z.string(), markerSetSchema).nullable().default(null),
    "hires-tile-size": hoconInt().default(32),
    "lowres-tile-size": hoconInt().default(500),
    "lod-count": hoconInt().default(3),
    "lod-factor": hoconInt().default(5),
});

export type MapConfig = z.infer<typeof mapConfigSchema>;

const GROUPS: readonly GroupMeta[] = [
    { id: "world", label: "World" },
    { id: "presentation", label: "How the map is presented" },
    { id: "lighting", label: "Light and colour" },
    { id: "caves", label: "Cave removal" },
    { id: "chunks", label: "Which chunks get rendered" },
    { id: "mask", label: "Render mask" },
    { id: "views", label: "Views" },
    { id: "storage", label: "Storage" },
    { id: "markers", label: "Static markers" },
    { id: "tiles", label: "Tile geometry", description: "Not present in upstream's template. Changing any of these invalidates every tile of this map." },
];

/** The wording upstream uses for a setting that costs a full re-render. */
const RE_RENDER = "Changing this value requires a re-render of the map.";

const FIELDS: readonly FieldMeta[] = [
    {
        path: "loader",
        key: "loader",
        segments: ["loader"],
        javaField: "loader",
        label: "World loader",
        doc: [
            "The world format BlueMap reads this map's world with.",
            "Not present in upstream's template. BlueMap's registry currently holds one loader, 'anvil', which is also the default.",
        ].join("\n"),
        group: "world",
        control: { kind: "select", allowCustom: true, options: WORLD_LOADER_OPTIONS },
        default: "bluemap:anvil",
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: true,
        invalidationNote: "Reading the world with a different loader produces different blocks, so every tile would have to be rendered again.",
        advanced: true,
    },
    {
        path: "world",
        key: "world",
        segments: ["world"],
        javaField: "world",
        label: "World folder",
        doc: [
            "The path to the save folder of the world to render.",
            "If this is not defined (commented out or removed), the map will be only registered to the webserver and the webapp",
            "but not rendered or loaded by BlueMap. This can be used to display a map that has been rendered somewhere else.",
        ].join("\n"),
        group: "world",
        control: { kind: "path", select: "directory", relativeToWorkingDirectory: true },
        default: null,
        templateValue: { value: "world", note: "A generated map config points at a folder named 'world' beside the working directory." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Pointing a map at a different world means every tile it already has belongs to the old one.",
        advanced: false,
    },
    {
        path: "dimension",
        key: "dimension",
        segments: ["dimension"],
        javaField: "dimension",
        label: "Dimension",
        doc: [
            'The dimension of the world. Can be "minecraft:overworld", "minecraft:the_nether", "minecraft:the_end",',
            "or any dimension key introduced by a mod or datapack.",
        ].join("\n"),
        group: "world",
        control: { kind: "select", allowCustom: true, options: DIMENSION_OPTIONS },
        default: null,
        templateValue: { value: "minecraft:overworld", note: "The generated overworld, nether and end configs each name their own dimension." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "A different dimension is a different world; the existing tiles are of the old one.",
        advanced: false,
    },
    {
        path: "dimension-type",
        key: "dimension-type",
        segments: ["dimension-type"],
        javaField: "dimensionType",
        label: "Dimension type",
        doc: [
            'The dimension-type of the world. Can be "minecraft:overworld", "minecraft:the_nether", "minecraft:the_end", "minecraft:overworld_caves",',
            "or any dimension-type key introduced by a datapack.",
            "Setting this value is usually not needed! In most cases BlueMap can detect this value automatically from the world-files.",
            "Default is the detected dimension-type",
        ].join("\n"),
        group: "world",
        control: { kind: "select", allowCustom: true, options: DIMENSION_TYPE_OPTIONS },
        default: null,
        templateValue: { value: null, note: "The template only writes this key when the dimension type differs from the dimension key, so a generated file usually omits it." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "The dimension type sets the world's height range and whether it has a sky, both of which are baked into rendered tiles.",
        advanced: true,
    },
    {
        path: "name",
        key: "name",
        segments: ["name"],
        javaField: "name",
        label: "Display name",
        doc: [
            "The display name of this map (how this map will be named on the webapp).",
            "You can change this at any time.",
            "Default is the id of this map",
        ].join("\n"),
        group: "presentation",
        control: { kind: "text" },
        default: null,
        templateValue: { value: "Overworld", note: "A generated config names the map after its dimension." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "sorting",
        key: "sorting",
        segments: ["sorting"],
        javaField: "sorting",
        label: "Sort order",
        doc: [
            "A lower value makes the map appear first (in lists and menus), a higher value makes it appear later.",
            "The value needs to be an integer but it can be negative.",
            "You can change this at any time.",
            "Default is 0",
        ].join("\n"),
        group: "presentation",
        control: integerControl({ step: 1 }),
        default: 0,
        templateValue: { value: 0, note: "Generated configs use 0 for the overworld, 100 for the nether and 200 for the end." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "start-pos",
        key: "start-pos",
        segments: ["start-pos"],
        javaField: "startPos",
        label: "Starting position",
        doc: [
            "The position in the world where the map will be centered on when you open it.",
            "You can change this at any time.",
            "Default is { x: 0, z: 0 }",
        ].join("\n"),
        group: "presentation",
        control: { kind: "vector", integer: true, axes: [{ key: "x", label: "X" }, { key: "z", label: "Z" }] },
        default: { x: 0, z: 0 },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "sky-color",
        key: "sky-color",
        segments: ["sky-color"],
        javaField: "skyColor",
        label: "Sky colour",
        doc: ["The color of the sky as a hex-color.", "You can change this at any time.", 'Default is "#7dabff"'].join("\n"),
        group: "lighting",
        control: { kind: "color", alpha: false },
        default: "#7dabff",
        templateValue: { value: "#7dabff", note: "The generated nether config uses #290000 and the end config #080010." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "void-color",
        key: "void-color",
        segments: ["void-color"],
        javaField: "voidColor",
        label: "Void colour",
        doc: ["The color of the void as a hex-color.", "You can change this at any time.", 'Default is "#000000"'].join("\n"),
        group: "lighting",
        control: { kind: "color", alpha: false },
        default: "#000000",
        templateValue: { value: "#000000", note: "The generated nether config uses #150000 and the end config #080010." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "sky-light",
        key: "sky-light",
        segments: ["sky-light"],
        javaField: "skyLight",
        label: "Sky light",
        doc: [
            "Defines the initial sky light strength the map will be set to when it is opened.",
            "0 is no sky light, 1 is fully lit up.",
            "You can change this at any time.",
            "Default is 1",
        ].join("\n"),
        group: "lighting",
        control: sliderControl({ min: 0, max: 1, step: 0.05, integer: false }),
        default: 1,
        advisory: { min: 0, max: 1, note: "Upstream describes 0 as no sky light and 1 as fully lit up." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "ambient-light",
        key: "ambient-light",
        segments: ["ambient-light"],
        javaField: "ambientLight",
        label: "Ambient light",
        doc: [
            "Defines the ambient light strength that every block is receiving, regardless of the sunlight/blocklight.",
            "0 is no ambient light, 1 is fully lit up.",
            "You can change this at any time.",
            "Default is 0",
        ].join("\n"),
        group: "lighting",
        control: sliderControl({ min: 0, max: 1, step: 0.05, integer: false }),
        default: 0,
        advisory: { min: 0, max: 1, note: "Upstream describes 0 as no ambient light and 1 as fully lit up." },
        templateValue: { value: 0.1, note: "The generated overworld config uses 0.1; the nether and end configs use 0.6." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "remove-caves-below-y",
        key: "remove-caves-below-y",
        segments: ["remove-caves-below-y"],
        javaField: "removeCavesBelowY",
        label: "Remove caves below Y",
        doc: [
            "BlueMap tries to omit all blocks that are below this Y-level and are not visible from above ground.",
            "More specifically, block faces that have a sunlight/skylight value of 0 are removed.",
            "This improves the performance of the map on slower devices by a lot, but might cause some blocks to disappear that should normally be visible.",
            RE_RENDER,
            "Set to a very high value to remove caves everywhere (e.g. 10000).",
            "Set to a very low value to remove nothing and render all caves (e.g. -10000).",
            "Default is 55 (slightly below water-level).",
        ].join("\n"),
        group: "caves",
        control: integerControl({ step: 1, unit: "Y" }),
        default: 55,
        templateValue: { value: 55, note: "The generated overworld config uses 55; the nether and end configs use -10000, which renders everything." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        advanced: false,
    },
    {
        path: "cave-detection-ocean-floor",
        key: "cave-detection-ocean-floor",
        segments: ["cave-detection-ocean-floor"],
        javaField: "caveDetectionOceanFloor",
        label: "Cave detection ocean floor offset",
        doc: [
            'This is the amount of blocks relative to the "ocean floor" heightmap that the cave detection will start at.',
            "Everything above that (heightmap relative) y-level will not be removed.",
            "Comment or set to a very high value to disable using the ocean floor heightmap for cave detection.",
            RE_RENDER,
            "Defaults to 10000 (disabled).",
        ].join("\n"),
        group: "caves",
        control: integerControl({ step: 1, unit: "blocks" }),
        default: 10000,
        templateValue: { value: -5, note: "The template writes -5, not the Java default of 10000, so a generated map has ocean-floor cave detection switched on." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        advanced: false,
    },
    {
        path: "cave-detection-uses-block-light",
        key: "cave-detection-uses-block-light",
        segments: ["cave-detection-uses-block-light"],
        javaField: "caveDetectionUsesBlockLight",
        label: "Use block light for cave detection",
        doc: [
            'With this value set to true, BlueMap also uses the block light value (additionally to the sky light) to "detect caves"',
            "(see the option above: remove-caves-below-y).",
            RE_RENDER,
            "Default is false",
        ].join("\n"),
        group: "caves",
        control: SWITCH,
        default: false,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        advanced: false,
    },
    {
        path: "min-inhabited-time",
        key: "min-inhabited-time",
        segments: ["min-inhabited-time"],
        javaField: "minInhabitedTime",
        label: "Minimum inhabited time",
        doc: [
            'The minimum "inhabitedTime" value that a chunk must have to be rendered.',
            'The "inhabitedTime" value of a chunk refers to the cumulative number of ticks players have been near this chunk.',
            "If you set this to a value greater than 0, BlueMap will only render chunks that players have visited already.",
            "Default is 0 (all generated chunks).",
        ].join("\n"),
        group: "chunks",
        control: integerControl({ min: 0, step: 1, unit: "ticks" }),
        default: 0,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        invalidationNote: "Raising this hides chunks that are already rendered; BlueMap updates the map rather than forcing a full re-render.",
        advanced: false,
    },
    {
        path: "min-inhabited-time-radius",
        key: "min-inhabited-time-radius",
        segments: ["min-inhabited-time-radius"],
        javaField: "minInhabitedTimeRadius",
        label: "Minimum inhabited time radius",
        doc: [
            "How many chunks around a chunk that passes the inhabited-time test are also rendered.",
            "Not present in upstream's template. Defaults to 0, meaning only the chunk itself.",
        ].join("\n"),
        group: "chunks",
        control: integerControl({ min: 0, step: 1, unit: "chunks" }),
        default: 0,
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "render-mask",
        key: "render-mask",
        segments: ["render-mask"],
        javaField: "renderMask",
        label: "Render mask",
        doc: [
            "With the render-mask you can limit the map render.",
            "This can be used to render only a certain part of a world or ignore the Nether's ceiling.",
            "If you change the render-mask, BlueMap automatically tries to update the map,",
            "including deleting map tiles which are outside the new limits.",
            'You can use "/bluemap fix-edges <map>" to fix any remaining issues.',
            "",
            "Please check out the wiki for more detailed information on how to configure this:",
            "https://bluemap.bluecolored.de/wiki/customization/Masks.html",
            "",
            "Default is no mask, BlueMap will render everything that exists.",
        ].join("\n"),
        group: "mask",
        control: { kind: "mask-list" },
        default: [],
        templateValue: {
            value: [],
            note: "The template writes an empty box with every bound commented out. The generated nether config adds a subtractive box over Y 90 to 127 to cut the ceiling away.",
        },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        invalidationNote: "BlueMap updates the map and deletes tiles outside the new limits rather than re-rendering everything. Run fix-edges afterwards if edges look wrong.",
        advanced: false,
    },
    {
        path: "render-edges",
        key: "render-edges",
        segments: ["render-edges"],
        javaField: "renderEdges",
        label: "Render mask edges as solid",
        doc: [
            "Using this, BlueMap pretends that every Block outside of the defined render-mask is AIR,",
            "this means you can see the blocks where the world is cut (instead of having a see-through/xray view).",
            "This only has an effect if you set some render-mask above.",
            RE_RENDER,
            "Default is true",
        ].join("\n"),
        group: "mask",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        advanced: false,
    },
    {
        path: "edge-light-strength",
        key: "edge-light-strength",
        segments: ["edge-light-strength"],
        javaField: "edgeLightStrength",
        label: "Edge light strength",
        doc: [
            "The sun-light strength that blocks at map edges will receive if render-edges is enabled.",
            "Should be a value between 0 and 15.",
            "Default is 15",
        ].join("\n"),
        group: "mask",
        control: sliderControl({ min: 0, max: 15, step: 1, integer: true }),
        default: 15,
        advisory: { min: 0, max: 15, note: "Upstream says this should be a value between 0 and 15." },
        templateValue: { value: 8, note: "The template writes 8, not the Java default of 15." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Not stated upstream. The value is baked into the edge geometry when a tile is rendered, so existing edge tiles keep the old lighting until they are re-rendered.",
        advanced: false,
    },
    {
        path: "enable-perspective-view",
        key: "enable-perspective-view",
        segments: ["enable-perspective-view"],
        javaField: "enablePerspectiveView",
        label: "Perspective view",
        doc: [
            "Whether the perspective view will be enabled for this map.",
            "Changing this to true requires a re-render of the map, only if the hires-layer is enabled and free-flight view is disabled.",
            "Default is true",
        ].join("\n"),
        group: "views",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Only when switching it on, and only if the hires layer is enabled and free-flight view is disabled.",
        advanced: false,
    },
    {
        path: "enable-flat-view",
        key: "enable-flat-view",
        segments: ["enable-flat-view"],
        javaField: "enableFlatView",
        label: "Flat view",
        doc: [
            "Whether the flat (isometric, top-down) view will be enabled for this map.",
            "Having only flat-view enabled while disabling free-flight and perspective will speed up the render and reduce the maps storage size.",
            "Default is true",
        ].join("\n"),
        group: "views",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "enable-free-flight-view",
        key: "enable-free-flight-view",
        segments: ["enable-free-flight-view"],
        javaField: "enableFreeFlightView",
        label: "Free-flight view",
        doc: [
            "Whether the free-flight view will be enabled for this map.",
            "Changing this to true requires a re-render of the map, only if the hires-layer is enabled and perspective view is disabled.",
            "Default is true",
        ].join("\n"),
        group: "views",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Only when switching it on, and only if the hires layer is enabled and perspective view is disabled.",
        advanced: false,
    },
    {
        path: "enable-hires",
        key: "enable-hires",
        segments: ["enable-hires"],
        javaField: "enableHires",
        label: "Hires layer",
        doc: [
            "Whether the hires-layer will be enabled.",
            "Disabling this will speed up rendering and reduce the size of the map files a lot.",
            "But you will not be able to see the full 3D models if you zoom in on the map.",
            "Changing this to false will not remove any existing tiles, existing tiles just won't get updated anymore.",
            "Changing this to true will require a re-render of the map.",
            "Default is true",
        ].join("\n"),
        group: "views",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Only when switching it on. Switching it off leaves the existing tiles in place, they just stop being updated.",
        advanced: false,
    },
    {
        path: "check-for-removed-regions",
        key: "check-for-removed-regions",
        segments: ["check-for-removed-regions"],
        javaField: "checkForRemovedRegions",
        label: "Check for removed regions",
        doc: [
            "Whether an update also looks for region files that have been deleted, so their tiles can be removed.",
            "Not present in upstream's template. Defaults to true.",
        ].join("\n"),
        group: "chunks",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "storage",
        key: "storage",
        segments: ["storage"],
        javaField: "storage",
        label: "Storage",
        doc: [
            "This defines the storage-config that will be used to save this map.",
            "You can find your storage configs next to this config file in the 'storages'-folder.",
            "Changing this value requires a re-render of the map. The map in the old storage will not be deleted.",
            'Default is "file"',
        ].join("\n"),
        group: "storage",
        control: { kind: "select", allowCustom: true, options: [{ value: "file", label: "file" }, { value: "sql", label: "sql" }] },
        default: "file",
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "The map in the old storage is not deleted, so nothing is lost; it just has to be rendered again into the new one.",
        advanced: false,
    },
    {
        path: "ignore-missing-light-data",
        key: "ignore-missing-light-data",
        segments: ["ignore-missing-light-data"],
        javaField: "ignoreMissingLightData",
        label: "Render chunks with no light data",
        doc: [
            "Normally BlueMap detects if a chunk has not yet generated its light data and omits rendering those chunks.",
            "If this is set to true BlueMap will render Chunks even if there is no light data!",
            "This can be useful for example if some mod prevents light data from being saved correctly.",
            "However, this also has a few drawbacks:",
            ' - Cave rendering will always be enabled (BlueMap is using the sky light data to "detect caves").',
            " - Everything will be rendered fully lit (sky light value of 15, looks similar to having night vision).",
            " - Night mode might not work correctly.",
            "Default is false (wait for light data).",
        ].join("\n"),
        group: "chunks",
        control: SWITCH,
        default: false,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: true,
        invalidationNote: "Not stated upstream. Chunks skipped for missing light data are rendered once this is on, and chunks already rendered under the old setting keep their old lighting.",
        advanced: false,
    },
    {
        path: "marker-sets",
        key: "marker-sets",
        segments: ["marker-sets"],
        javaField: "markerSets",
        label: "Static marker sets",
        doc: [
            "Here you can define any static marker-sets with markers that should be displayed on the map.",
            "You can change this at any time.",
            "If you need dynamic markers, you can use any plugin that integrates with BlueMap's API.",
            "Here is a list: https://bluemap.bluecolored.de/community/3rdPartySupport.html",
            "",
            "Please check out the wiki for information on how to configure this:",
            "https://bluemap.bluecolored.de/wiki/customization/Markers.html",
        ].join("\n"),
        group: "markers",
        control: { kind: "marker-sets" },
        default: null,
        templateValue: { value: null, note: "The template writes an empty marker-sets block containing only a link to the wiki." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "hires-tile-size",
        key: "hires-tile-size",
        segments: ["hires-tile-size"],
        javaField: "hiresTileSize",
        label: "Hires tile size",
        doc: [
            "The edge length in blocks of one hires tile.",
            "Not present in upstream's template, and marked in the Java class as a hidden config field. Defaults to 32.",
        ].join("\n"),
        group: "tiles",
        control: integerControl({ min: 1, step: 1, unit: "blocks" }),
        default: 32,
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: true,
        invalidationNote: "This is the tile grid itself. Every existing tile is the wrong size the moment it changes.",
        advanced: true,
    },
    {
        path: "lowres-tile-size",
        key: "lowres-tile-size",
        segments: ["lowres-tile-size"],
        javaField: "lowresTileSize",
        label: "Lowres tile size",
        doc: [
            "The edge length in pixels of one lowres tile.",
            "Not present in upstream's template, and marked in the Java class as a hidden config field. Defaults to 500.",
        ].join("\n"),
        group: "tiles",
        control: integerControl({ min: 1, step: 1, unit: "pixels" }),
        default: 500,
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: true,
        invalidationNote: "This is the tile grid itself. Every existing tile is the wrong size the moment it changes.",
        advanced: true,
    },
    {
        path: "lod-count",
        key: "lod-count",
        segments: ["lod-count"],
        javaField: "lodCount",
        label: "Level-of-detail count",
        doc: [
            "How many lowres levels of detail BlueMap generates.",
            "Not present in upstream's template, and marked in the Java class as a hidden config field. Defaults to 3.",
        ].join("\n"),
        group: "tiles",
        control: integerControl({ min: 1, step: 1, unit: "levels" }),
        default: 3,
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: true,
        invalidationNote: "Changes the lowres pyramid, so the existing lowres tiles no longer describe the same levels.",
        advanced: true,
    },
    {
        path: "lod-factor",
        key: "lod-factor",
        segments: ["lod-factor"],
        javaField: "lodFactor",
        label: "Level-of-detail factor",
        doc: [
            "How much coarser each lowres level is than the one before it.",
            "Not present in upstream's template, and marked in the Java class as a hidden config field. Defaults to 5.",
        ].join("\n"),
        group: "tiles",
        control: integerControl({ min: 2, step: 1 }),
        default: 5,
        commentedOutInTemplate: false,
        hidden: true,
        invalidatesTiles: true,
        invalidationNote: "Changes the lowres pyramid, so the existing lowres tiles no longer describe the same levels.",
        advanced: true,
    },
];

/**
 * Keys that used to configure the render bounds directly, before render masks
 * replaced them. BlueMap does not ignore these: it refuses to start.
 */
const LEGACY_MESSAGE = [
    "Your map-configuration is outdated!",
    "Looks like you updated BlueMap but did not follow the upgrade-instructions correctly.",
    "To fix your config, make sure to follow all relevant upgrade-instructions from BlueMap's changelogs.",
    "You can find them here: https://github.com/BlueMap-Minecraft/BlueMap/releases",
].join("\n");

const LEGACY_KEYS: readonly LegacyKey[] = ["min-x", "max-x", "min-z", "max-z", "min-y", "max-y"].map((key) => ({ key, message: LEGACY_MESSAGE }));

export const mapConfigDescriptor: ConfigFileDescriptor<MapConfig> = {
    id: "map",
    title: "Map",
    description: "One file per map. Everything about which world is rendered, how it looks, and which parts of it exist on the map.",
    location: { pattern: "maps/<id>.conf", cardinality: "many", folder: "maps" },
    schema: mapConfigSchema,
    fields: FIELDS,
    groups: GROUPS,
    legacyKeys: LEGACY_KEYS,
    template: MAP_TEMPLATE,
};
